import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { timingSafeEqual } from 'node:crypto';
import { acceptArivePayload, createAriveStore, integrationHealth } from './src/integrations/arive.js';
import { loadRuntimeConfig, postgresPoolOptions } from './src/config/runtime.js';
import { EntraOidcAuth, parseCookies, secureCookie } from './src/auth/entra-oidc.js';
import { previewVictoryEvent } from './src/domain/victory.js';
import { buildMorningCommandBrief, buildPipelineWaitingSummary } from './src/domain/admin-command-center.js';
import { enrichPrivateQueue, enrichPrivateAdminCommandCenter, manualTaskOptions, createPrivateManualTask, cancelPrivateManualTask } from './src/storage/private-my-work.js';

const root = join(process.cwd(), 'public');
const types = { '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.css':'text/css; charset=utf-8' };
const json = (res, status, body) => { res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}); res.end(JSON.stringify(body)); };
async function readJson(req) {
  let data=''; for await (const part of req) { data+=part; if (data.length>1_000_000) throw new Error('Payload too large'); }
  if (!data) throw new Error('Request body is required'); try { return JSON.parse(data); } catch { throw new Error('Invalid JSON'); }
}
const authorized=(req,secret)=>{if(!secret)return true;const supplied=req.headers.authorization?.replace(/^Bearer\s+/i,'')??req.headers['x-hfn-webhook-secret'];if(!supplied)return false;const a=Buffer.from(supplied),b=Buffer.from(secret);return a.length===b.length&&timingSafeEqual(a,b);};
const redirect=(res,location,headers={})=>{res.writeHead(302,{Location:location,...headers});res.end();};
export function createHfnServer({ store=createAriveStore(), environment=process.env.NODE_ENV ?? 'development', webhookSecret, auth=null }={}) {
  return createServer(async (req,res) => {
    const url=new URL(req.url,'http://localhost');
    try {
      const cookies=parseCookies(req.headers.cookie),employee=auth?await auth.session(cookies):null;
      if(req.method==='GET'&&url.pathname==='/auth/login'){if(!auth)return json(res,503,{ok:false,error:'Authentication is not configured'});return redirect(res,await auth.loginUrl());}
      if(req.method==='GET'&&url.pathname==='/auth/callback'){if(!auth)return json(res,503,{ok:false,error:'Authentication is not configured'});const completed=await auth.complete({state:url.searchParams.get('state'),code:url.searchParams.get('code')});return redirect(res,'/my-work',{'Set-Cookie':secureCookie('hfn_session',completed.sessionToken,{production:environment==='production',maxAge:28800})});}
      if(req.method==='POST'&&url.pathname==='/auth/logout'){if(auth)await auth.logout(cookies);return json(res,200,{ok:true});}
      if(req.method==='GET'&&url.pathname==='/api/auth/me'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});return json(res,200,{ok:true,employee:{email:employee.email,displayName:employee.displayName,role:employee.role}});}
      if(req.method==='GET'&&url.pathname==='/api/my-work'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});const queue=store.myWorkQueue??store.processorWorkQueue;if(!queue)return json(res,503,{ok:false,error:'Work queue unavailable'});if(!['processor','processor_assistant','admin'].includes(employee.role))return json(res,403,{ok:false,error:'My Work is not available for this role'});const result=await queue.call(store,{employee,ownerEmail:employee.role==='admin'?url.searchParams.get('ownerEmail'):null});return json(res,200,store.pool?await enrichPrivateQueue(store.pool,result):result);}
      if(req.method==='GET'&&url.pathname==='/api/admin/command-center'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(employee.role!=='admin')return json(res,403,{ok:false,error:'Admin Command Center is not available for this role'});if(!store.adminCommandCenter)return json(res,503,{ok:false,error:'Admin Command Center unavailable'});const [result,health,dashboard,ctcPerformance,closingOutlook]=await Promise.all([store.adminCommandCenter({employee}),store.health?store.health():integrationHealth(store),store.dashboard?store.dashboard():null,store.ctcPerformanceSummary?store.ctcPerformanceSummary():null,store.closingOutlook?store.closingOutlook():null]);const privateResult=store.pool?await enrichPrivateAdminCommandCenter(store.pool,result):result;return json(res,200,{...privateResult,morningBrief:{...buildMorningCommandBrief({...result,ctcPerformance},dashboard,health),closingOutlook,pipelineWaiting:buildPipelineWaitingSummary(result.stageAging)},integrationHealth:health});}
      if(req.method==='GET'&&url.pathname==='/api/my-work/manual-options'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(!store.pool)return json(res,503,{ok:false,error:'Manual tasks unavailable'});return json(res,200,await manualTaskOptions(store.pool,employee));}
      if(req.method==='POST'&&url.pathname==='/api/my-work/manual-tasks'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(!store.pool)return json(res,503,{ok:false,error:'Manual tasks unavailable'});const body=await readJson(req);return json(res,200,await createPrivateManualTask(store.pool,{employee,loanId:body.loanId,title:body.title,assigneeEmail:body.assigneeEmail,dueAt:body.dueAt,priority:body.priority,note:body.note}));}
      if(req.method==='POST'&&url.pathname.startsWith('/api/my-work/manual-tasks/')&&url.pathname.endsWith('/cancel')){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(!store.pool)return json(res,503,{ok:false,error:'Manual tasks unavailable'});const taskId=decodeURIComponent(url.pathname.slice('/api/my-work/manual-tasks/'.length,-'/cancel'.length));return json(res,200,await cancelPrivateManualTask(store.pool,{employee,taskId}));}
      if(req.method==='GET'&&url.pathname==='/api/my-work/employees'){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(employee.role!=='admin')return json(res,403,{ok:false,error:'Management employee filters are not available for this role'});if(!store.myWorkEmployees)return json(res,503,{ok:false,error:'Employee filters unavailable'});return json(res,200,await store.myWorkEmployees({employee}));}
      if(req.method==='POST'&&url.pathname.startsWith('/api/my-work/tasks/')&&(url.pathname.endsWith('/docs-sent-to-notary')||url.pathname.endsWith('/docs-signed'))){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});const docsSent=url.pathname.endsWith('/docs-sent-to-notary'),suffix=docsSent?'/docs-sent-to-notary':'/docs-signed',taskId=decodeURIComponent(url.pathname.slice('/api/my-work/tasks/'.length,-suffix.length)),method=docsSent?'markDocsSentToNotary':'markDocsSigned';if(!store[method])return json(res,503,{ok:false,error:'Task actions unavailable'});return json(res,200,await store[method]({employee,taskId}));}
      if(req.method==='POST'&&url.pathname.startsWith('/api/my-work/tasks/')&&url.pathname.includes('/checklist-items/')){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(!store.mutateWorkflowChecklist)return json(res,503,{ok:false,error:'Task actions unavailable'});const prefix='/api/my-work/tasks/',split=url.pathname.slice(prefix.length).split('/checklist-items/'),taskId=decodeURIComponent(split[0]),checklistItemId=decodeURIComponent(split[1]??''),body=await readJson(req);return json(res,200,await store.mutateWorkflowChecklist({employee,taskId,checklistItemId,checklistState:body.state}));}
      if(req.method==='POST'&&url.pathname.startsWith('/api/my-work/tasks/')&&url.pathname.endsWith('/actions')){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});const taskId=decodeURIComponent(url.pathname.slice('/api/my-work/tasks/'.length,-'/actions'.length)),body=await readJson(req);if(body.action==='appraisal_phase'){if(!store.setAppraisalFollowUpPhase)return json(res,503,{ok:false,error:'Task actions unavailable'});return json(res,200,await store.setAppraisalFollowUpPhase({employee,taskId,phase:body.phase}));}if(['review_no_action','review_add_to_next_uw_submission','review_issue_found'].includes(body.action)){if(!store.mutateProcessorReview)return json(res,503,{ok:false,error:'Task actions unavailable'});return json(res,200,await store.mutateProcessorReview({employee,taskId,action:body.action,note:body.note??null}));}if(!store.mutateWorkflowTask)return json(res,503,{ok:false,error:'Task actions unavailable'});return json(res,200,await store.mutateWorkflowTask({employee,taskId,action:body.action,blockedCategory:body.blockedCategory??null,note:body.note??null,checklistItemId:body.checklistItemId??null,checklistState:body.checklistState??null}));}
      if(req.method==='POST'&&url.pathname.startsWith('/api/my-work/loans/')&&url.pathname.endsWith('/manual-workflows')){if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(!store.createManualWorkflow)return json(res,503,{ok:false,error:'Manual workflows unavailable'});const loanId=decodeURIComponent(url.pathname.slice('/api/my-work/loans/'.length,-'/manual-workflows'.length)),body=await readJson(req);return json(res,200,await store.createManualWorkflow({employee,loanId,type:body.type,checklist:Array.isArray(body.checklist)?body.checklist:[]}));}
      if(req.method==='GET'&&url.pathname==='/my-work'){if(!employee)return redirect(res,'/auth/login');const body=await readFile(join(root,'my-work.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(body);}
      if(req.method==='GET'&&url.pathname==='/admin'){if(!employee)return redirect(res,'/auth/login');if(employee.role!=='admin')return json(res,403,{ok:false,error:'Admin Command Center is not available for this role'});const body=await readFile(join(root,'admin-command-center.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(body);}
      if (req.method==='POST' && (url.pathname==='/api/integrations/arive/events' || (environment!=='production' && url.pathname==='/api/development/arive/synthetic-event'))) {
        if(url.pathname==='/api/integrations/arive/events'&&!authorized(req,webhookSecret))return json(res,401,{ok:false,error:'Unauthorized'});
        const payload=await readJson(req), result=store.receive?await store.receive(payload):acceptArivePayload(store,payload);
        return json(res,result.ok?200:400,{ok:result.ok,outcome:result.outcome,tasksCreated:result.tasksCreated,error:result.ok?undefined:result.error});
      }
      if (req.method==='GET' && url.pathname==='/api/integrations/arive/health') return json(res,200,store.health?await store.health():integrationHealth(store));
      if (req.method==='GET' && url.pathname==='/api/dashboard') return store.dashboard?json(res,200,await store.dashboard()):json(res,404,{ok:false,error:'Live dashboard unavailable in demo mode'});
      if (req.method==='GET' && url.pathname==='/api/victory-events') return store.victoryEvents?json(res,200,await store.victoryEvents(url.searchParams.get('after'))):json(res,200,{events:[]});
      if (environment!=='production' && req.method==='GET' && url.pathname==='/api/development/victory-events/preview') return json(res,200,{event:previewVictoryEvent(url.searchParams.get('type')??undefined)});
      if (req.method==='GET' && url.pathname==='/api/admin/funding-goals') { if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(employee.role!=='admin')return json(res,403,{ok:false,error:'Funding goals are available to Admin only'});if(!store.monthlyFundingGoal)return json(res,404,{ok:false,error:'Funding goals unavailable'});const now=new Date(),year=Number(url.searchParams.get('year')??now.getFullYear()),month=Number(url.searchParams.get('month')??now.getMonth()+1);return json(res,200,await store.monthlyFundingGoal(year,month)); }
      if (req.method==='PUT' && url.pathname==='/api/admin/funding-goals') { if(!employee)return json(res,401,{ok:false,error:'Sign in required'});if(employee.role!=='admin')return json(res,403,{ok:false,error:'Funding goals are available to Admin only'});if(!store.saveMonthlyFundingGoal)return json(res,404,{ok:false,error:'Funding goals unavailable'});const body=await readJson(req);return json(res,200,await store.saveMonthlyFundingGoal({year:Number(body.year),month:Number(body.month),fundedLoanGoal:Number(body.fundedLoanGoal),fundedVolumeGoal:Number(body.fundedVolumeGoal)})); }
      if (req.method==='GET' && url.pathname==='/api/loans') return json(res,200,store.listLoans?await store.listLoans(url.searchParams.get('q')??''):{source:environment==='production'?'live':'demo',loans:[]});
      if (req.method==='GET' && url.pathname.startsWith('/api/loans/')) { if(!store.loanDetail)return json(res,404,{ok:false,error:'Live loan detail unavailable in demo mode'});const detail=await store.loanDetail(decodeURIComponent(url.pathname.slice('/api/loans/'.length)));return detail?json(res,200,detail):json(res,404,{ok:false,error:'Loan not found'}); }
      if (req.method==='GET' && (url.pathname==='/health'||url.pathname==='/api/health')) return json(res,200,{ok:true,status:'healthy'});
      if (url.pathname.startsWith('/api/')) return json(res,404,{ok:false,error:'Not found'});
      const requested=url.pathname==='/'?'index.html':url.pathname.slice(1), path=normalize(join(root,requested));
      if (!path.startsWith(root)) return res.writeHead(403).end('Forbidden');
      let body=await readFile(path); if(environment==='production'&&requested==='index.html')body=Buffer.from(body.toString().replace('</head>','<script>window.HFN_PRODUCTION=true;</script></head>')); res.writeHead(200,{'Content-Type':types[extname(path)]??'application/octet-stream'}); res.end(body);
    } catch (error) { const clientError=['Invalid JSON','Request body is required','Payload too large'].includes(error.message);if(!clientError)console.error(JSON.stringify({route:url.pathname,errorName:error?.name??'Error',errorMessage:error?.message??'Unknown error',stack:error?.stack??null,authDiagnostic:error?.safeAuthDiagnostic}));json(res,clientError?400:500,{ok:false,error:clientError?error.message:'Internal error'}); }
  });
}
export function listenHfnServer(server, config, onListening=()=>{}) { return server.listen({ port:config.port, host:'0.0.0.0' },onListening); }
if (process.argv[1]===fileURLToPath(import.meta.url)) { const config=loadRuntimeConfig(); let store=createAriveStore(),auth=null; if(!config.demo){const {Pool}=await import('pg');const {PostgresAriveRepository}=await import('./src/storage/postgres-arive.js');store=new PostgresAriveRepository(new Pool(postgresPoolOptions(config)));await store.initialize();auth=new EntraOidcAuth({repository:store,config});}const server=createHfnServer({store,auth,environment:config.production?'production':'development',webhookSecret:config.webhookSecret});listenHfnServer(server,config,()=>console.log(`HFN Command Center running at http://0.0.0.0:${config.port}`)); }
