import { dueAt } from './sla.js';

export const workflowTaskStates=Object.freeze(['action_required','waiting','follow_up_due','due_soon','past_due','blocked','escalated','completed','cancelled','not_applicable']);
export const workflowOrigins=Object.freeze(['automatic','manual','conditional']);
export const ownerRoles=Object.freeze(['processor','processor_assistant','loan_officer','management','system']);
export const blockerCategories=Object.freeze(['borrower','vendor','lender','ARIVE/system','internal','other']);
export function validateBlockDetails({blockedCategory,note}) { if(!blockerCategories.includes(blockedCategory))throw new Error('Blocked category is required');const blockedReason=typeof note==='string'?note.trim():'';if(!blockedReason)throw new Error('Blocked reason is required');if(blockedReason.length>500)throw new Error('Blocked reason must be 500 characters or fewer');return {blockedCategory,blockedReason}; }
export const safeWorkflowMetadata=value=>Object.fromEntries(Object.entries(value??{}).filter(([key,item])=>['sourceEvent','tracker','conditionReference','checklistContext','previousState','resultingState','lastFollowUpAt','nextFollowUpAt','followUpCount','waitingOn','followUpPhase','workflowCycle','reviewOutcome','assignmentException'].includes(key)&&(typeof item!=='object'||key==='checklistContext')));
export const businessDeadline=(start,businessDays,calendar)=>businessDays===null||businessDays===undefined?null:dueAt(start,{kind:'businessHours',value:businessDays*8.5},calendar).toISOString();
export const nextFollowUpAt=(from,cadenceBusinessDays,calendar)=>cadenceBusinessDays?businessDeadline(from,cadenceBusinessDays,calendar):null;
export function createWorkflowTask({id,loanId,definition,createdAt,ownerEmail,ownerName,kpiEligible,calendar,origin='automatic',metadata}) { return {id,loanId,taskType:definition.type,title:definition.title,ownerRole:definition.ownerRole,ownerEmail:ownerEmail??null,ownerName:ownerName??null,origin,state:'action_required',createdAt,dueAt:businessDeadline(createdAt,definition.businessDays,calendar),completedAt:null,kpiEligible:Boolean(kpiEligible),followUpCadenceBusinessDays:definition.followUpBusinessDays??null,nextFollowUpAt:null,waitingOn:definition.waitingOn??null,metadata:safeWorkflowMetadata(metadata)}; }
export function transitionTask(task,{state,at,reason=null,actorEmail=null}) { if(!workflowTaskStates.includes(state))throw new Error('Invalid workflow task state');if((state==='completed'||state==='cancelled')&&!at)throw new Error('Completion timestamp is required');return {...task,state,completedAt:state==='completed'?at:task.completedAt,blockedAt:state==='blocked'?at:task.blockedAt,blockedReason:state==='blocked'?reason:task.blockedReason,blockedByEmail:state==='blocked'?actorEmail:task.blockedByEmail}; }
export function recordFollowUp(task,{at,calendar,actorEmail=null,note=null}) { if(!task.followUpCadenceBusinessDays)throw new Error('Task has no follow-up cadence');const cadence=task.taskType==='request_insurance_eoi'&&(task.followUpCount??0)>0?2:task.followUpCadenceBusinessDays;return {...task,state:'waiting',lastFollowUpAt:at,nextFollowUpAt:nextFollowUpAt(at,cadence,calendar),followUpCount:(task.followUpCount??0)+1,lastFollowUpByEmail:actorEmail,lastFollowUpNote:note}; }
export const checklistComplete=items=>items.length>0&&items.every(item=>item.state==='completed'||item.state==='not_applicable');
