import test from 'node:test'; import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs'; import { createAriveStore, normalizeArivePayload } from '../src/integrations/arive.js';
const sample={ariveLoanId:'arive-guid-123',ariveDisplayLoanId:'HFN-26098',currentLoanStatus_status:'UNDERWRITING_SUBMITTED',currentLoanStatus_date:'2026-09-14T10:00:00-07:00',modifiedDateTime:'2026-09-14T10:01:00-07:00',loanProcessorName:'Susan Vu',loanOfficerAssistantName:'Joshua Quintanilla',loanTeamUsers:[{name:'Susan Vu',role:'Processor'}],borrowerFirstName:'sensitive-name',borrowerEmail:'sensitive-email'};
async function apiTest(run) { const store=createAriveStore(), server=createHfnServer({store,environment:'development'}); await new Promise(resolve=>server.listen(0,resolve)); const port=server.address().port; try { await run(`http://127.0.0.1:${port}`,store); } finally { await new Promise(resolve=>server.close(resolve)); } }
const post=(base,path,body)=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('valid payload is redacted, normalized, and creates assistant milestones', async()=>apiTest(async(base,store)=>{const response=await post(base,'/api/integrations/arive/events',sample);const body=await response.json();const audit=store.audits[0];assert.equal(response.status,200);assert.equal(body.outcome,'processed');assert.equal(body.tasksCreated,6);assert.equal(store.audits.length,1);assert.equal(audit.payload.borrowerEmail,undefined);assert.equal(audit.payload.borrowerFirstName,undefined);assert.match(audit.payloadHash,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(audit.payload).includes('sensitive-email'),false);assert.equal(store.loans.get('arive-guid-123').ariveDisplayLoanId,'HFN-26098');assert.equal(store.integration.tasks.length,6);}));
test('duplicate payload is audited but does not duplicate events or tasks', async()=>apiTest(async(base,store)=>{await post(base,'/api/integrations/arive/events',sample);const response=await post(base,'/api/integrations/arive/events',sample);const body=await response.json();assert.equal(body.outcome,'duplicate');assert.equal(store.audits.length,2);assert.equal(store.integration.events.length,1);assert.equal(store.integration.tasks.length,6);}));
test('malformed JSON receives a safe failure response', async()=>apiTest(async(base,store)=>{const response=await fetch(base+'/api/integrations/arive/events',{method:'POST',headers:{'Content-Type':'application/json'},body:'not-json'});assert.equal(response.status,400);assert.equal((await response.json()).error,'Invalid JSON');assert.equal(store.audits.length,0);}));
test('missing ARIVE System GUID is retained in audit as a failure', async()=>apiTest(async(base,store)=>{const response=await post(base,'/api/integrations/arive/events',{...sample,ariveLoanId:undefined});const body=await response.json();assert.equal(response.status,400);assert.equal(body.error,'Missing ARIVE System GUID');assert.equal(store.audits[0].status,'failed');}));
test('development endpoint accepts only a synthetic local submission in non-production', async()=>apiTest(async(base)=>{const response=await post(base,'/api/development/arive/synthetic-event',sample);assert.equal(response.status,200);}));
test('integration health never exposes raw borrower fields', async()=>apiTest(async(base)=>{await post(base,'/api/integrations/arive/events',sample);const health=await (await fetch(base+'/api/integrations/arive/health')).json();assert.equal(JSON.stringify(health).includes('sensitive-email'),false);assert.equal(health.eventsProcessed,1);}));
test('selects only the exact AssistantProcessor loan-team role',()=>{const loan=normalizeArivePayload({processorName:'Susan Vu',processorEmail:'susan@hfn.test',loanOfficerAssistantName:'Ignore Me',loanTeamUser1FirstName:'Loan',loanTeamUser1LastName:'Officer Assistant',loanTeamUser1Email:'lo-assistant@hfn.test',loanTeamUser1Role:'Assistant',loanTeamUser2FirstName:'Process',loanTeamUser2LastName:'Assistant',loanTeamUser2Email:'processor-assistant@hfn.test',loanTeamUser2Role:'AssistantProcessor'});assert.equal(loan.assistant,'Process Assistant');assert.equal(loan.assistantEmail,'processor-assistant@hfn.test');assert.equal(loan.processorEmail,'susan@hfn.test');assert.equal(loan.assistantException,null);});
test('ignores Assistant and dedicated LO Assistant fields for Processor Assistant ownership',()=>{const loan=normalizeArivePayload({loanOfficerAssistantName:'Dedicated LO Assistant',loanOfficerAssistantEmail:'dedicated-lo@hfn.test',loanTeamUser1FirstName:'Loan',loanTeamUser1LastName:'Officer',loanTeamUser1Email:'team-lo@hfn.test',loanTeamUser1Role:'Assistant'});assert.equal(loan.assistant,null);assert.equal(loan.assistantEmail,null);assert.match(loan.assistantException,/No Loan Team User with Loan Role AssistantProcessor/);});
test('flags zero or multiple AssistantProcessor role assignments without guessing',()=>{const missing=normalizeArivePayload({loanTeamUser1Role:'Processor'}),multiple=normalizeArivePayload({loanTeamUser1FirstName:'First',loanTeamUser1Role:'AssistantProcessor',loanTeamUser2FirstName:'Second',loanTeamUser2Role:'AssistantProcessor'});assert.equal(missing.assistant,null);assert.match(missing.assistantException,/No Loan Team/);assert.equal(multiple.assistant,null);assert.equal(multiple.assistantEmail,null);assert.match(multiple.assistantException,/Multiple Loan Team/);});
test('maps safe CD dates while retaining Initial CD as the SLA completion source',()=>{const dates=normalizeArivePayload({appraisalOrderedDate:'2026-09-01',appraisalReceivedDate:'2026-09-02',titleOrderedDate:'2026-09-03',titleReceivedDate:'2026-09-04',hoiOrderedDate:'2026-09-05',hoiReceivedDate:'2026-09-06',initialCDSentDate:'2026-09-08',mostRecentCDSentDate:'2026-09-10',initialCDSignedDate:'2026-09-09',mostRecentCDSignedDate:'2026-09-11'}).milestoneDates;assert.equal(dates.initialCDSentDate,'2026-09-08');assert.equal(dates.mostRecentCDSentDate,'2026-09-10');assert.equal(dates.initialCDSignedDate,'2026-09-09');assert.equal(dates.mostRecentCDSignedDate,'2026-09-11');assert.equal(dates.appraisalReceivedDate,'2026-09-02');});
