import test from 'node:test'; import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs'; import { createAriveStore } from '../src/integrations/arive.js';
const sample={ariveLoanId:'arive-guid-123',ariveDisplayLoanId:'HFN-26098',currentLoanStatus_status:'UNDERWRITING_SUBMITTED',currentLoanStatus_date:'2026-09-14T10:00:00-07:00',modifiedDateTime:'2026-09-14T10:01:00-07:00',loanProcessorName:'Susan Vu',loanOfficerAssistantName:'Joshua Quintanilla',loanTeamUsers:[{name:'Susan Vu',role:'Processor'}],borrowerFirstName:'sensitive-name',borrowerEmail:'sensitive-email'};
async function apiTest(run) { const store=createAriveStore(), server=createHfnServer({store,environment:'development'}); await new Promise(resolve=>server.listen(0,resolve)); const port=server.address().port; try { await run(`http://127.0.0.1:${port}`,store); } finally { await new Promise(resolve=>server.close(resolve)); } }
const post=(base,path,body)=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('valid payload is redacted, normalized, and creates assistant milestones', async()=>apiTest(async(base,store)=>{const response=await post(base,'/api/integrations/arive/events',sample);const body=await response.json();const audit=store.audits[0];assert.equal(response.status,200);assert.equal(body.outcome,'processed');assert.equal(body.tasksCreated,8);assert.equal(store.audits.length,1);assert.equal(audit.payload.borrowerEmail,undefined);assert.equal(audit.payload.borrowerFirstName,undefined);assert.match(audit.payloadHash,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(audit.payload).includes('sensitive-email'),false);assert.equal(store.loans.get('arive-guid-123').ariveDisplayLoanId,'HFN-26098');assert.equal(store.integration.tasks.length,8);}));
test('duplicate payload is audited but does not duplicate events or tasks', async()=>apiTest(async(base,store)=>{await post(base,'/api/integrations/arive/events',sample);const response=await post(base,'/api/integrations/arive/events',sample);const body=await response.json();assert.equal(body.outcome,'duplicate');assert.equal(store.audits.length,2);assert.equal(store.integration.events.length,1);assert.equal(store.integration.tasks.length,8);}));
test('malformed JSON receives a safe failure response', async()=>apiTest(async(base,store)=>{const response=await fetch(base+'/api/integrations/arive/events',{method:'POST',headers:{'Content-Type':'application/json'},body:'not-json'});assert.equal(response.status,400);assert.equal((await response.json()).error,'Invalid JSON');assert.equal(store.audits.length,0);}));
test('missing ARIVE System GUID is retained in audit as a failure', async()=>apiTest(async(base,store)=>{const response=await post(base,'/api/integrations/arive/events',{...sample,ariveLoanId:undefined});const body=await response.json();assert.equal(response.status,400);assert.equal(body.error,'Missing ARIVE System GUID');assert.equal(store.audits[0].status,'failed');}));
test('development endpoint accepts only a synthetic local submission in non-production', async()=>apiTest(async(base)=>{const response=await post(base,'/api/development/arive/synthetic-event',sample);assert.equal(response.status,200);}));
test('integration health never exposes raw borrower fields', async()=>apiTest(async(base)=>{await post(base,'/api/integrations/arive/events',sample);const health=await (await fetch(base+'/api/integrations/arive/health')).json();assert.equal(JSON.stringify(health).includes('sensitive-email'),false);assert.equal(health.eventsProcessed,1);}));
