import test from 'node:test'; import assert from 'node:assert/strict';
import { assistantMilestones, emptyIntegrationState, ingestEvent } from '../src/domain/events.js'; import { dueAt, slaState } from '../src/domain/sla.js';
const hfn={businessStart:{hour:8,minute:30},businessEnd:{hour:17,minute:0},workdays:[1,2,3,4,5],holidays:[]}; const local=(y,m,d,h,min=30)=>new Date(y,m-1,d,h,min);
const submission={loanId:'assistant-loan',type:'UNDERWRITING_SUBMITTED',occurredAt:'2026-09-11T08:30:00-07:00',receivedAt:'2026-09-11T08:31:00-07:00',source:'test',sourceEventId:'uw-1',metadata:{assistantId:'Joshua Quintanilla'}};
test('all eight assistant milestones originate from underwriting submission',()=>{const result=ingestEvent(emptyIntegrationState(),submission);assert.equal(result.tasksCreated,8);assert.deepEqual(result.state.tasks.map(t=>t.type),assistantMilestones.map(m=>m.type));});
test('one, five, and seven business-day deadlines skip weekends',()=>{assert.equal(dueAt(local(2026,9,11,16),{kind:'businessHours',value:8.5},hfn).getDate(),14);assert.equal(dueAt(local(2026,9,11,16),{kind:'businessHours',value:42.5},hfn).getDate(),18);assert.equal(dueAt(local(2026,9,11,16),{kind:'businessHours',value:59.5},hfn).getDate(),22);});
test('configured holiday extends the assistant deadline',()=>{const calendar={...hfn,holidays:['2026-09-14']};assert.equal(dueAt(local(2026,9,11,16),{kind:'businessHours',value:8.5},calendar).getDate(),15);});
test('completion before and after SLA are distinguished',()=>{const rule={kind:'businessHours',value:8.5};assert.equal(slaState(local(2026,9,14,8,30),local(2026,9,14,16),rule,undefined,hfn).state,'completed');assert.equal(slaState(local(2026,9,14,8,30),local(2026,9,15,9),rule,undefined,hfn).state,'breached');});
test('missing tracker completion remains outstanding',()=>{const result=ingestEvent(emptyIntegrationState(),submission);assert.equal(result.state.tasks.every(task=>task.completedAt===null&&task.status==='open'),true);});
