import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PostgresAriveRepository } from '../src/storage/postgres-arive.js';
import { businessDeadline } from '../src/domain/workflow-engine.js';
import { defaultCalendar } from '../src/domain/sla.js';

class ConditionsExecutor {
  constructor({kpiEligible=true}={}){this.kpiEligible=kpiEligible;this.tasks=[];this.history=[];}
  async connect(){return this;}
  release(){}
  task(id){return this.tasks.find(task=>task.id===id);}
  add(task){if(this.tasks.some(existing=>existing.loan_id===task.loan_id&&existing.task_type===task.task_type&&existing.workflow_cycle===task.workflow_cycle))return null;this.tasks.push(task);return task;}
  async query(sql,args=[]){
    const q=sql.toLowerCase();
    if(['begin','commit','rollback'].includes(q))return {rows:[],rowCount:0};
    if(q.startsWith('select kpi_tracking_started_at'))return {rows:[{kpi_eligible:this.kpiEligible}],rowCount:1};
    if(q.startsWith('select id,task_type,state from workflow_tasks'))return {rows:this.tasks.filter(task=>task.loan_id===args[0]&&['review_approval_conditions','borrower_conditions_follow_up','resubmit_to_underwriting','ctc_follow_up'].includes(task.task_type)&&!['completed','cancelled','not_applicable'].includes(task.state)),rowCount:0};
    if(q.startsWith('select coalesce(max(workflow_cycle)')){const max=Math.max(0,...this.tasks.filter(task=>task.loan_id===args[0]&&task.task_type==='review_approval_conditions').map(task=>task.workflow_cycle));return {rows:[{cycle:max+1}],rowCount:1};}
    if(q.startsWith('select * from workflow_tasks where id=')){const task=this.task(args[0]);return {rows:task?[task]:[],rowCount:task?1:0};}
    if(q.startsWith('select task_type,state,last_follow_up_at')){const task=this.task(args[0]);return {rows:task?[task]:[],rowCount:task?1:0};}
    if(q.startsWith('select to_state from workflow_task_history'))return {rows:[],rowCount:0};
    if(q.startsWith('select id,loan_id,task_type,origin')){const task=this.task(args[0]);return {rows:task?[task]:[],rowCount:task?1:0};}
    if(q.startsWith('select loan_id,workflow_cycle,origin')){const task=[...this.tasks].filter(item=>item.loan_id===args[0]&&item.task_type==='resubmit_to_underwriting').sort((a,b)=>b.workflow_cycle-a.workflow_cycle)[0];return {rows:task?[task]:[],rowCount:task?1:0};}
    if(q.startsWith('insert into workflow_task_history')){this.history.push({taskId:args[1],action:args[3],fromState:args[4],toState:args[5],actorEmail:args[6],metadata:args[8]});return {rows:[],rowCount:1};}
    if(q.startsWith('insert into workflow_tasks')){
      let task;
      if(q.includes("'review_approval_conditions'"))task={id:args[0],loan_id:args[1],task_type:'review_approval_conditions',workflow_cycle:args[2],origin:'automatic',owner_role:'processor',owner_email:args[3],owner_name:args[4],state:'action_required',created_at:args[5],due_at:args[6],kpi_eligible:args[7],metadata:args[8]};
      else if(q.includes("'borrower_conditions_follow_up'"))task={id:args[0],loan_id:args[1],task_type:'borrower_conditions_follow_up',workflow_cycle:args[2],origin:args[3],owner_role:'processor',owner_email:args[4],owner_name:args[5],state:'waiting',created_at:args[6],due_at:args[7],kpi_eligible:args[8],waiting_on:'borrower',follow_up_cadence_business_days:2,next_follow_up_at:args[9],follow_up_count:0,metadata:args[10]};
      else if(q.includes("'resubmit_to_underwriting'"))task={id:args[0],loan_id:args[1],task_type:'resubmit_to_underwriting',workflow_cycle:args[2],origin:args[3],owner_role:'processor',owner_email:args[4],owner_name:args[5],state:'action_required',created_at:args[6],due_at:args[7],kpi_eligible:args[8],metadata:args[9]};
      else if(q.includes("'ctc_follow_up'"))task={id:args[0],loan_id:args[1],task_type:'ctc_follow_up',workflow_cycle:args[2],origin:args[3],owner_role:'processor',owner_email:args[4],owner_name:args[5],state:'waiting',created_at:args[6],due_at:args[7],kpi_eligible:args[8],waiting_on:'underwriter',follow_up_cadence_business_days:2,next_follow_up_at:args[9],follow_up_count:0,metadata:args[10]};
      else return {rows:[],rowCount:0};
      const created=this.add(task);return {rows:created?[created]:[],rowCount:created?1:0};
    }
    if(q.startsWith("update workflow_tasks set state='completed',completed_at=$2")&&q.includes('where id=$1')){const task=this.task(args[0]);if(task){task.state='completed';task.completed_at=args[1];}return {rows:[],rowCount:task?1:0};}
    if(q.startsWith("update workflow_tasks set state='waiting',last_follow_up_at")){const task=this.task(args[0]);task.state='waiting';task.last_follow_up_at=args[1];task.next_follow_up_at=args[2];task.follow_up_count=(task.follow_up_count??0)+1;return {rows:[],rowCount:1};}
    if(q.startsWith("update workflow_tasks set state='completed',completed_at=$3")){const changed=this.tasks.filter(task=>task.loan_id===args[0]&&task.task_type===args[1]&&!['completed','cancelled','not_applicable'].includes(task.state));for(const task of changed){task.state='completed';task.completed_at=args[2];}return {rows:changed,rowCount:changed.length};}
    if(q.startsWith("update workflow_tasks set state=case when task_type='ctc_follow_up'")){const changed=this.tasks.filter(task=>task.loan_id===args[0]&&['borrower_conditions_follow_up','resubmit_to_underwriting','ctc_follow_up'].includes(task.task_type)&&!['completed','cancelled','not_applicable'].includes(task.state));for(const task of changed){task.state=task.task_type==='ctc_follow_up'?'completed':'cancelled';if(task.task_type==='ctc_follow_up')task.completed_at=args[1];}return {rows:changed,rowCount:changed.length};}
    if(q.startsWith("update workflow_tasks set state='cancelled'")){const task=this.task(args[0]);if(task)task.state='cancelled';return {rows:[],rowCount:task?1:0};}
    if(q.startsWith('select state from workflow_task_checklist_items'))return {rows:[],rowCount:0};
    throw new Error(`Unexpected SQL: ${sql}`);
  }
}

const processor={email:'processor@hfn.test',displayName:'Processor',role:'processor'},at='2026-09-11T23:00:00.000Z';
async function start(executor){const repository=new PostgresAriveRepository(executor);await repository.syncWorkflowForEvent(executor,{loanId:'loan-1',eventType:'APPROVED_WITH_CONDITION',occurredAt:at,processor:'Processor',processorEmail:processor.email});return repository;}

test('approval review starts one KPI-eligible processor conditions cycle with a one-business-day deadline',async()=>{const db=new ConditionsExecutor(),repository=await start(db),review=db.tasks[0];assert.equal(review.task_type,'review_approval_conditions');assert.equal(review.owner_role,'processor');assert.equal(review.kpi_eligible,true);assert.equal(review.due_at,businessDeadline(at,1,defaultCalendar));assert.equal(db.history[0].action,'conditions_cycle_started');assert.equal((await repository.startConditionsCycle(db,{loanId:'loan-1',occurredAt:at,processor:'Processor',processorEmail:processor.email,kpiEligible:true})),null);assert.equal(db.tasks.length,1);});

test('review completion creates a waiting borrower conditions follow-up atomically and records two-business-day cadence',async()=>{const db=new ConditionsExecutor(),repository=await start(db),review=db.tasks[0];await repository.mutateWorkflowTask({employee:processor,taskId:review.id,action:'review_complete',at});const follow=db.tasks.find(task=>task.task_type==='borrower_conditions_follow_up');assert.equal(review.state,'completed');assert.equal(follow.state,'waiting');assert.equal(follow.next_follow_up_at,businessDeadline(at,2,defaultCalendar));assert.equal(follow.follow_up_cadence_business_days,2);assert.equal(follow.waiting_on,'borrower');assert.equal(follow.kpi_eligible,true);});

test('conditions follow-up repeats every two business days and ready-for-resubmittal creates same-day re-submit work',async()=>{const db=new ConditionsExecutor(),repository=await start(db),review=db.tasks[0];await repository.mutateWorkflowTask({employee:processor,taskId:review.id,action:'review_complete',at});const follow=db.tasks.find(task=>task.task_type==='borrower_conditions_follow_up'),followAt='2026-09-15T23:00:00.000Z';await repository.mutateWorkflowTask({employee:processor,taskId:follow.id,action:'follow_up',at:followAt});assert.equal(follow.follow_up_count,1);assert.equal(follow.last_follow_up_at,followAt);assert.equal(follow.next_follow_up_at,businessDeadline(followAt,2,defaultCalendar));assert.equal(db.history.at(-1).action,'followed_up');await repository.mutateWorkflowTask({employee:processor,taskId:follow.id,action:'ready_for_resubmittal',at:followAt});const resubmit=db.tasks.find(task=>task.task_type==='resubmit_to_underwriting');assert.equal(follow.state,'completed');assert.equal(resubmit.due_at,businessDeadline(followAt,0,defaultCalendar));assert.equal(resubmit.kpi_eligible,true);});

test('ARIVE re-submittal completes re-submit, creates CTC follow-up, and CTC closes the obsolete cycle',async()=>{const db=new ConditionsExecutor(),repository=await start(db),review=db.tasks[0];await repository.mutateWorkflowTask({employee:processor,taskId:review.id,action:'review_complete',at});const follow=db.tasks.find(task=>task.task_type==='borrower_conditions_follow_up');await repository.mutateWorkflowTask({employee:processor,taskId:follow.id,action:'ready_for_resubmittal',at});const resubmit=db.tasks.find(task=>task.task_type==='resubmit_to_underwriting'),resubmittedAt='2026-09-15T23:00:00.000Z';await repository.syncWorkflowForEvent(db,{loanId:'loan-1',eventType:'RE_SUBMITTAL',occurredAt:resubmittedAt,processor:'Processor',processorEmail:processor.email});const ctc=db.tasks.find(task=>task.task_type==='ctc_follow_up');assert.equal(resubmit.state,'completed');assert.equal(ctc.state,'waiting');assert.equal(ctc.next_follow_up_at,businessDeadline(resubmittedAt,2,defaultCalendar));await repository.mutateWorkflowTask({employee:processor,taskId:ctc.id,action:'follow_up',at:'2026-09-17T23:00:00.000Z'});assert.equal(ctc.follow_up_count,1);await repository.syncWorkflowForEvent(db,{loanId:'loan-1',eventType:'CLEAR_TO_CLOSE',occurredAt:'2026-09-18T23:00:00.000Z',processor:'Processor',processorEmail:processor.email});assert.equal(ctc.state,'completed');assert.ok(db.history.some(entry=>entry.action==='completed_by_arive_event'));});

test('a later legitimate approval cycle cancels prior CTC follow-up, starts cycle two, and historical cycles remain KPI neutral',async()=>{const db=new ConditionsExecutor({kpiEligible:false}),repository=await start(db),review=db.tasks[0];await repository.mutateWorkflowTask({employee:processor,taskId:review.id,action:'review_complete',at});const follow=db.tasks.find(task=>task.task_type==='borrower_conditions_follow_up');await repository.mutateWorkflowTask({employee:processor,taskId:follow.id,action:'ready_for_resubmittal',at});await repository.syncWorkflowForEvent(db,{loanId:'loan-1',eventType:'RE_SUBMITTAL',occurredAt:'2026-09-15T23:00:00.000Z',processor:'Processor',processorEmail:processor.email});const ctc=db.tasks.find(task=>task.task_type==='ctc_follow_up');await repository.syncWorkflowForEvent(db,{loanId:'loan-1',eventType:'APPROVED_WITH_CONDITION',occurredAt:'2026-09-16T23:00:00.000Z',processor:'Processor',processorEmail:processor.email});const second=db.tasks.find(task=>task.task_type==='review_approval_conditions'&&task.workflow_cycle===2);assert.equal(ctc.state,'cancelled');assert.equal(second.kpi_eligible,false);assert.ok(db.tasks.every(task=>task.kpi_eligible===false));assert.equal(db.tasks.filter(task=>task.state!=='completed'&&task.state!=='cancelled'&&task.task_type==='review_approval_conditions').length,1);});

test('conditions migration permits sequential cycles but never multiple open copies, and workflow data stays out of processor SLA aggregates',async()=>{const [migration,repository]=await Promise.all([readFile(new URL('../db/019_conditions_follow_up_workflow.sql',import.meta.url),'utf8'),readFile(new URL('../src/storage/postgres-arive.js',import.meta.url),'utf8')]);assert.match(migration,/workflow_cycle integer/i);assert.match(migration,/workflow_tasks_one_open_cycle/i);assert.match(repository,/019_conditions_follow_up_workflow/);const dashboard=repository.slice(repository.indexOf('async dashboard()'),repository.indexOf('async health()'));assert.doesNotMatch(dashboard,/workflow_tasks/);});
