import test from 'node:test';
import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs';
import { readFile } from 'node:fs/promises';

test('dashboard failure stays private to the client and logs safe route diagnostics',async()=>{const original=console.error,logs=[];console.error=value=>logs.push(value);const server=createHfnServer({environment:'production',webhookSecret:'secret',store:{dashboard:async()=>{throw new Error('monthly funding query failed');}}});await new Promise(resolve=>server.listen(0,resolve));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/dashboard`),body=await response.json();assert.equal(response.status,500);assert.deepEqual(body,{ok:false,error:'Internal error'});assert.match(logs[0],/api\/dashboard/);assert.match(logs[0],/monthly funding query failed/);}finally{console.error=original;await new Promise(resolve=>server.close(resolve));}});
test('callback keeps token-exchange failures private while logging only sanitized Microsoft diagnostics',async()=>{const original=console.error,logs=[];console.error=value=>logs.push(value);const auth={session:async()=>null,complete:async()=>{const error=new Error('Microsoft token exchange failed');error.name='EntraTokenExchangeError';error.safeAuthDiagnostic={provider:'microsoft',httpStatus:400,error:'invalid_client',errorDescription:'AADSTS7000215 client_secret=[redacted]'};throw error;}};const server=createHfnServer({environment:'production',webhookSecret:'secret',auth});await new Promise(resolve=>server.listen(0,resolve));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/auth/callback?code=authorization-code&state=state`),body=await response.json();assert.equal(response.status,500);assert.deepEqual(body,{ok:false,error:'Internal error'});assert.match(logs[0],/auth\/callback/);assert.match(logs[0],/invalid_client/);assert.match(logs[0],/httpStatus/);assert.doesNotMatch(logs[0],/authorization-code/);}finally{console.error=original;await new Promise(resolve=>server.close(resolve));}});
test('dashboard count query delegates Funded MTD to the shared aggregate',async()=>{const source=await readFile(new URL('../src/storage/postgres-arive.js',import.meta.url),'utf8');assert.match(source,/m\.state='breached'/);assert.match(source,/this\.fundingSummary\(year,month\)/);assert.match(source,/fundedMtd:fundingGoal\.fundedCount\.actual/);assert.match(source,/t\.completed_at is null/);assert.doesNotMatch(source,/funded_mtd/);assert.doesNotMatch(source,/and state='breached'/);});
test('Past SLA counts only KPI-eligible breaches while Attention Needed remains operational',async()=>{const source=await readFile(new URL('../src/storage/postgres-arive.js',import.meta.url),'utf8');assert.match(source,/task_loan\.kpi_tracking_started_at is not null and t\.kpi_eligible and t\.completed_at is null/);assert.match(source,/sla_loan\.kpi_tracking_started_at is not null and m\.state='breached'/);assert.match(source,/assistantExceptions\.rows/);});
