import test from 'node:test';
import assert from 'node:assert/strict';
import { EntraOidcAuth } from '../src/auth/entra-oidc.js';

const config={microsoftClientId:'client-id',microsoftClientSecret:'secret-value',microsoftTenantId:'tenant-id',microsoftRedirectUri:'https://hfn-command-center.onrender.com/auth/callback',sessionSecret:'session-secret'};
const repository={createOidcLoginState:async()=>{},consumeOidcLoginState:async()=>({expires_at:'2099-01-01T00:00:00.000Z',code_verifier:'pkce-verifier'})};

test('Entra authorization request uses tenant v2 endpoint, configured redirect URI, and PKCE',async()=>{const auth=new EntraOidcAuth({repository,config});const url=new URL(await auth.loginUrl());assert.equal(url.origin,'https://login.microsoftonline.com');assert.equal(url.pathname,'/tenant-id/oauth2/v2.0/authorize');assert.equal(url.searchParams.get('client_id'),'client-id');assert.equal(url.searchParams.get('redirect_uri'),config.microsoftRedirectUri);assert.equal(url.searchParams.get('scope'),'openid profile email');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.ok(url.searchParams.get('code_challenge'));});

test('Entra token exchange uses form encoding and preserves only redacted Microsoft diagnostics',async()=>{let request;const auth=new EntraOidcAuth({repository,config,fetchImpl:async(url,options)=>{request={url,options};return {ok:false,status:400,json:async()=>({error:'invalid_client',error_description:'AADSTS7000215 client_secret=secret-value code=authorization-code access_token=eyJ.token.value'})};}});await assert.rejects(auth.complete({state:'state',code:'authorization-code'}),error=>{assert.equal(error.name,'EntraTokenExchangeError');assert.equal(error.message,'Microsoft token exchange failed');assert.deepEqual(error.safeAuthDiagnostic.provider,'microsoft');assert.equal(error.safeAuthDiagnostic.httpStatus,400);assert.equal(error.safeAuthDiagnostic.error,'invalid_client');assert.doesNotMatch(error.safeAuthDiagnostic.errorDescription,/secret-value|authorization-code|eyJ/);return true;});assert.equal(request.url,'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token');assert.equal(request.options.headers['Content-Type'],'application/x-www-form-urlencoded');const body=new URLSearchParams(request.options.body);assert.equal(body.get('client_id'),'client-id');assert.equal(body.get('client_secret'),'secret-value');assert.equal(body.get('redirect_uri'),config.microsoftRedirectUri);assert.equal(body.get('code_verifier'),'pkce-verifier');});
