import test from 'node:test';
import assert from 'node:assert/strict';
import { assistantMetricKeys, metricOwner, metricResult, overallResult, processorMetricKey, processorMetricKeys } from '../src/domain/kpi-metrics.js';
import { buildLiveDashboard } from '../src/domain/dashboard.js';

test('Setup and disclosures belong only to the Processor Assistant',()=>{assert.equal(metricOwner('setup'),'assistant');assert.equal(metricOwner('disclosures'),'assistant');assert.equal(processorMetricKeys.includes('setup'),false);assert.equal(processorMetricKeys.includes('disclosures'),false);});
test('UW submission, approval, conditions, and CTC belong only to Processor',()=>{for(const metric of processorMetricKeys)assert.equal(metricOwner(metric),'processor');});
test('Processor metric aliases normalize without admitting Setup or Disclosure work',()=>{assert.equal(processorMetricKey('uw_submission'),'uw_submission');assert.equal(processorMetricKey('clear_to_close'),'ctc');assert.equal(processorMetricKey('setup'),null);assert.equal(processorMetricKey('disclosures'),null);});
test('individual and overall Assistant SLA use eligible observation numerators and denominators',()=>{const observations=[{metricKey:'title_ordered',kpiEligible:true,dueAt:'2026-09-11T17:00:00Z',completedAt:'2026-09-11T16:00:00Z'},{metricKey:'title_ordered',kpiEligible:true,dueAt:'2026-09-11T17:00:00Z',completedAt:'2026-09-12T16:00:00Z'},{metricKey:'appraisal_ordered',kpiEligible:false,dueAt:'2026-09-11T17:00:00Z',completedAt:null}];assert.deepEqual(metricResult(observations,'title_ordered'),{numerator:1,denominator:2,percentage:50});assert.deepEqual(overallResult(observations),{numerator:1,denominator:2,percentage:50});assert.equal(metricResult(observations,'setup').percentage,null);});
test('all eight Assistant KPI metrics are defined',()=>assert.equal(assistantMetricKeys.length,8));
test('Assistant-owned Setup and Disclosure observations cannot enter Processor KPI results',()=>{const dashboard=buildLiveDashboard({counts:{},processorLoans:[],processorSlas:[{processor:'Susan Vu',metricKey:'setup',state:'breached'},{processor:'Susan Vu',metricKey:'disclosures',state:'breached'},{processor:'Susan Vu',metricKey:'uw_submission',state:'completed',dueAt:'2026-09-11T17:00:00Z',evaluatedAt:'2026-09-11T16:00:00Z'}],funded:[],assistantTasks:[],attention:[]});const susan=dashboard.processors.find(item=>item.name==='Susan Vu');assert.deepEqual(susan.uwSubmitSla,{numerator:1,denominator:1,percentage:100});assert.deepEqual(susan.overallSla,{numerator:1,denominator:1,percentage:100});assert.equal(susan.pastSla,0);});
test('KPI-eligible Assistant Setup and Disclosure observations appear only in Assistant performance',()=>{const dashboard=buildLiveDashboard({counts:{},processorLoans:[],processorSlas:[],funded:[],assistantTasks:[],assistantSlas:[{assistant:'Joshua Quintanilla',taskType:'setup',state:'completed',dueAt:'2026-09-11T17:00:00Z',evaluatedAt:'2026-09-11T16:00:00Z'},{assistant:'Joshua Quintanilla',taskType:'disclosures',state:'breached',dueAt:'2026-09-11T17:00:00Z',evaluatedAt:'2026-09-12T16:00:00Z'}],attention:[]});const joshua=dashboard.assistants.find(item=>item.name==='Joshua Quintanilla');assert.deepEqual(joshua.individualSlas.setup,{numerator:1,denominator:1,percentage:100});assert.deepEqual(joshua.individualSlas.disclosures,{numerator:0,denominator:1,percentage:0});assert.deepEqual(joshua.overallSla,{numerator:1,denominator:2,percentage:50});});
test('Assistant dashboard data has performance scores but no ranking field',()=>{const dashboard=buildLiveDashboard({counts:{},processorLoans:[],processorSlas:[],funded:[],assistantTasks:[{assistant:'Joshua Quintanilla',taskType:'title_ordered',applicableAt:'2026-09-11T08:30:00Z',dueAt:'2026-09-11T17:00:00Z',completedAt:'2026-09-11T16:00:00Z'}],attention:[]});const joshua=dashboard.assistants.find(item=>item.name==='Joshua Quintanilla');assert.equal(typeof joshua.score,'number');assert.equal('rank' in joshua,false);});
