import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PostgresAriveRepository } from '../src/storage/postgres-arive.js';

class RecoveryClient {
  constructor(){this.writes=0;this.rolledBack=false;this.taskOpen=true;this.initialOpen=false;this.finalOnly=false;this.snapshot={};this.audit=0;}
  release(){}
  async query(sql,args=[]){const q=sql.toLowerCase();if(q==='begin'||q==='commit')return {rowCount:0,rows:[]};if(q==='rollback'){this.rolledBack=true;return {rowCount:0,rows:[]};}if(q.includes('from loans where arive_display_loan_id'))return {rowCount:1,rows:[{id:'loan-1',arive_system_guid:'guid-1',arive_display_loan_id:'17512793',operational_snapshot:this.snapshot}]};if(q.includes("from inbound_events where source='zapier-arive'"))return this.finalOnly?{rowCount:1,rows:[{received_at:'2026-09-15T00:00:00Z',milestoneDates:{titleReceivedDate:'2026-09-15'},trackerContext:{}}]}:{rowCount:2,rows:[{received_at:'2026-09-13T23:42:49Z',milestoneDates:{titleOrderedDate:'2026-09-10',titleReceivedDate:'2026-09-11',appraisalReceivedDate:'2026-09-12'},trackerContext:{titleStatus:'RECEIVED',titleTrackerDate:'2026-09-11'}},{received_at:'2026-09-13T23:43:00Z',milestoneDates:{hoiReceivedDate:'2026-09-13'},trackerContext:{hoiStatus:'RECEIVED',hoiTrackerDate:'2026-09-13'}}]};if(q.startsWith('update loans set operational_snapshot')){this.writes++;this.snapshot=args[1];return {rowCount:1,rows:[]};}if(q.startsWith('select id,state,kpi_eligible from workflow_tasks')){const title=this.taskOpen&&args[1]==='title_follow_up',initial=this.initialOpen&&args[1]==='order_title_escrow';return {rowCount:title||initial?1:0,rows:title?[{id:'title-task',state:'waiting',kpi_eligible:false}]:initial?[{id:'order-title-task',state:'past_due',kpi_eligible:false}]:[]};}if(q.startsWith('select id from workflow_tasks'))return {rowCount:this.taskOpen&&args[1]==='title_follow_up'?1:0,rows:this.taskOpen&&args[1]==='title_follow_up'?[{id:'title-task'}]:[]};if(q.startsWith('update workflow_tasks set state=')){this.writes++;if(args[0]==='order-title-task')this.initialOpen=false;else this.taskOpen=false;return {rowCount:1,rows:[]};}if(q.startsWith('insert into workflow_task_history')){this.writes++;return {rowCount:1,rows:[]};}if(q.startsWith('select id,loan_id,task_type'))return {rowCount:1,rows:[{id:'title-task',loan_id:'loan-1',task_type:'title_follow_up'}]};if(q.startsWith('insert into operational_snapshot_recoveries')){this.writes++;this.audit++;return {rowCount:this.audit===1?1:0,rows:[]};}throw new Error(`Unexpected query: ${sql}`);}
}
class RecoveryPool {constructor(client){this.client=client;}async connect(){return this.client;}}

test('targeted recovery dry-run reads safe snapshots only and performs no writes',async()=>{const client=new RecoveryClient(),result=await new PostgresAriveRepository(new RecoveryPool(client)).recoverOperationalSnapshot({displayLoanId:'17512793',dryRun:true});assert.equal(result.eventsInspected,2);assert.equal(result.earliestEventAt,'2026-09-13T23:42:49Z');assert.equal(result.latestEventAt,'2026-09-13T23:43:00Z');assert.equal(result.recoveredOperationalSnapshot.milestoneDates.titleReceivedDate,'2026-09-11');assert.equal(result.recoveredOperationalSnapshot.milestoneDates.hoiReceivedDate,'2026-09-13');assert.ok(result.reconciliationCandidates.some(item=>item.taskType==='title_follow_up'));assert.equal(client.writes,0);assert.equal(client.rolledBack,true);});
test('targeted recovery dry-run recognizes a received-without-ordered Title repair without writing',async()=>{const client=new RecoveryClient();client.finalOnly=true;client.initialOpen=true;client.taskOpen=false;const result=await new PostgresAriveRepository(new RecoveryPool(client)).recoverOperationalSnapshot({displayLoanId:'17512793',dryRun:true});assert.deepEqual(result.reconciliationCandidates,[{taskType:'order_title_escrow',completedAt:null,authoritativeAt:'2026-09-15',evidence:'key_date',action:'arive_final_milestone_superseded_initial_task',orderedTimestamp:'unknown'}]);assert.equal(client.writes,0);assert.equal(client.rolledBack,true);});
test('targeted recovery applies transactionally, reconciles title follow-up, and is idempotent',async()=>{const client=new RecoveryClient(),repository=new PostgresAriveRepository(new RecoveryPool(client));const first=await repository.recoverOperationalSnapshot({displayLoanId:'17512793',dryRun:false});assert.equal(first.reconciledTasks[0].taskType,'title_follow_up');assert.equal(client.snapshot.trackerContext.titleStatus,'RECEIVED');assert.equal(client.taskOpen,false);const writes=client.writes,second=await repository.recoverOperationalSnapshot({displayLoanId:'17512793',dryRun:false});assert.deepEqual(second.reconciledTasks,[]);assert.equal(client.writes,writes+2);});
test('targeted recovery refuses missing loan scope, exposes no bulk command, and uses the external operator TLS helper',async()=>{await assert.rejects(()=>new PostgresAriveRepository(new RecoveryPool(new RecoveryClient())).recoverOperationalSnapshot({displayLoanId:'',dryRun:true}),/display loan ID/);const script=await readFile(new URL('../scripts/workflow-recover-operational-snapshot.mjs',import.meta.url),'utf8');assert.match(script,/--loan/);assert.match(script,/postgresOperatorPoolOptions/);assert.doesNotMatch(script,/--all|bulk/i);});
