import test from 'node:test';
import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs';

async function withServer(employee,run){const calls=[],auth={session:async()=>employee},store={processorWorkQueue:async input=>{calls.push(input);return {viewer:{email:input.employee.email,role:input.employee.role},tasks:[{displayLoanId:'12345678',title:'Submit loan to underwriting',priority:'past_due',state:'past_due',dueAt:'2026-09-12T17:00:00Z'}]}}},server=createHfnServer({store,auth,environment:'production',webhookSecret:'secret'});await new Promise(resolve=>server.listen(0,resolve));try{await run(`http://127.0.0.1:${server.address().port}`,calls);}finally{await new Promise(resolve=>server.close(resolve));}}
test('unauthenticated Processor My Work is denied',async()=>withServer(null,async base=>assert.equal((await fetch(`${base}/api/my-work`)).status,401)));
test('authorized Processor sees only their server-derived queue identity',async()=>withServer({email:'susan@hfn.test',displayName:'Susan',role:'processor'},async(base,calls)=>{const response=await fetch(`${base}/api/my-work?ownerEmail=elizabeth@hfn.test`),body=await response.json();assert.equal(response.status,200);assert.equal(calls[0].employee.email,'susan@hfn.test');assert.equal(calls[0].ownerEmail,null);assert.equal(body.tasks[0].displayLoanId,'12345678');assert.equal(JSON.stringify(body).includes('borrower'),false);}));
test('admin can request an all-processor or selected-processor view',async()=>withServer({email:'admin@hfn.test',displayName:'Admin',role:'admin'},async(base,calls)=>{await fetch(`${base}/api/my-work?ownerEmail=susan@hfn.test`);assert.equal(calls[0].ownerEmail,'susan@hfn.test');}));
test('Processor Assistant receives the same private My Work route without cross-employee selection',async()=>withServer({email:'assistant@hfn.test',displayName:'Assistant',role:'processor_assistant'},async(base,calls)=>{const response=await fetch(`${base}/api/my-work?ownerEmail=other@hfn.test`);assert.equal(response.status,200);assert.equal(calls[0].employee.email,'assistant@hfn.test');assert.equal(calls[0].ownerEmail,null);}));
