import test from 'node:test';
import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs';
import { createAriveStore } from '../src/integrations/arive.js';
import { buildLiveDashboard } from '../src/domain/dashboard.js';

async function withServer(run){const server=createHfnServer({store:createAriveStore(),environment:'production',webhookSecret:'secret'});await new Promise(resolve=>server.listen(0,resolve));try{await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
test('production never falls back to demo File Detail data or synthetic homepage rendering',async()=>withServer(async base=>{const loans=await (await fetch(base+'/api/loans')).json();const html=await (await fetch(base+'/')).text();assert.equal(loans.source,'live');assert.deepEqual(loans.loans,[]);assert.equal(JSON.stringify(loans).includes('HFN-2609'),false);assert.match(html,/HFN_PRODUCTION=true/);}));
test('insufficient live history renders configured dashboard rows as collecting data',()=>{const dashboard=buildLiveDashboard({counts:{activeLoans:1,newFiles:0,uwSubmitted:0,clearToClose:0,fundedMtd:0,pastSla:0},processorLoans:[{processor:'Susan Vu',currentStage:'UNDERWRITING_SUBMITTED'}],processorSlas:[],funded:[],assistantTasks:[],attention:[]});assert.equal(dashboard.processors.length,2);assert.equal(dashboard.processors[0].activeLoans,1);assert.equal(dashboard.processors[0].setupSla,undefined);assert.deepEqual(dashboard.assistants.map(item=>item.name),['Joshua Quintanilla','Sophia Gomez']);assert.equal(dashboard.assistants[0].score,'Collecting data');assert.equal(dashboard.assistants[0].rank,'—');assert.equal(dashboard.assistants[0].completionPercent,null);assert.equal(JSON.stringify(dashboard).includes('HFN-2609'),false);});
test('live completed assistant tasks populate real metrics without demo values',()=>{const dashboard=buildLiveDashboard({counts:{activeLoans:1,newFiles:0,uwSubmitted:1,clearToClose:0,fundedMtd:0,pastSla:0},processorLoans:[],processorSlas:[],funded:[],assistantTasks:[{assistant:'Joshua Quintanilla',applicableAt:'2026-09-10T17:00:00Z',dueAt:'2026-09-11T17:00:00Z',completedAt:'2026-09-11T16:00:00Z'}],attention:[]});const assistant=dashboard.assistants.find(item=>item.name==='Joshua Quintanilla');assert.equal(assistant.completionPercent,100);assert.equal(assistant.slaCompliancePercent,100);assert.notEqual(assistant.score,'Collecting data');});
test('first-seen downstream tasks remain operational but do not contaminate Assistant KPIs',()=>{const dashboard=buildLiveDashboard({counts:{activeLoans:1,newFiles:0,uwSubmitted:1,clearToClose:0,fundedMtd:0,pastSla:0},processorLoans:[],processorSlas:[],funded:[],assistantTasks:[{assistant:'Joshua Quintanilla',kpiEligible:false,applicableAt:'2026-09-01T17:00:00Z',dueAt:'2026-09-02T17:00:00Z',completedAt:null}],attention:[]});const assistant=dashboard.assistants.find(item=>item.name==='Joshua Quintanilla');assert.equal(assistant.activeTasks,0);assert.equal(assistant.score,'Collecting data');});
