import test from 'node:test';
import assert from 'node:assert/strict';
import { PostgresAriveRepository } from '../src/storage/postgres-arive.js';
import { goalWasCrossed, quickCtcElapsedCalendarDays, victorySettings } from '../src/domain/victory.js';
import { createHfnServer } from '../server.mjs';

class VictoryExecutor {
  constructor({underwritingSubmittedAt=null,afterCount=0,afterVolume=0,goalCount=null,goalVolume=null}={}){this.underwritingSubmittedAt=underwritingSubmittedAt;this.afterCount=afterCount;this.afterVolume=afterVolume;this.goalCount=goalCount;this.goalVolume=goalVolume;this.events=[];}
  async query(sql,params=[]){
    if(sql.startsWith('select state,loan_amount'))return {rows:[{state:'CA',loan_amount:'750000'}]};
    if(sql.startsWith('select occurred_at'))return {rows:this.underwritingSubmittedAt?[{occurred_at:this.underwritingSubmittedAt}]:[]};
    if(sql.startsWith('insert into victory_events')){const [,eventType,,displayLoanId,occurredAt,metadata,dedupeKey]=params;if(this.events.some(event=>event.dedupeKey===dedupeKey))return {rowCount:0,rows:[]};this.events.push({eventType,displayLoanId,occurredAt,metadata,dedupeKey});return {rowCount:1,rows:[{id:'event'}]};}
    if(sql.includes('monthly_funding_goals'))return {rows:this.goalCount===null?[]:[{fundedLoanGoal:this.goalCount,fundedVolumeGoal:this.goalVolume}]};
    if(sql.startsWith('with live'))return {rows:[{count:this.afterCount,volume:this.afterVolume,missingAmountCount:0}]};
    throw new Error(`Unexpected query: ${sql.slice(0,60)}`);
  }
}
test('newly funded loans create one borrower-safe Funded victory and dedupe by loan key',async()=>{const executor=new VictoryExecutor(),repository=new PostgresAriveRepository(executor);await repository.syncVictoryEvents(executor,{loanId:'loan-1',eventType:'LOAN_FUNDED',occurredAt:'2026-09-15T18:00:00Z',displayLoanId:'17567005'});await repository.syncVictoryEvents(executor,{loanId:'loan-1',eventType:'LOAN_FUNDED',occurredAt:'2026-09-15T18:00:00Z',displayLoanId:'17567005'});assert.equal(executor.events.length,1);assert.deepEqual(executor.events[0].metadata,{state:'CA',loanAmount:750000,elapsedCalendarDays:null,fundedCount:null,fundedVolume:null,goal:null,year:null,month:null});assert.doesNotMatch(JSON.stringify(executor.events[0]),/borrower|email|street/i);});
test('Quick CTC creates only inside the centralized calendar-day threshold and requires UW evidence',async()=>{const inside=new VictoryExecutor({underwritingSubmittedAt:'2026-09-01T18:00:00Z'}),repository=new PostgresAriveRepository(inside);await repository.syncVictoryEvents(inside,{loanId:'loan-2',eventType:'CLEAR_TO_CLOSE',occurredAt:'2026-09-07T18:00:00Z',displayLoanId:'17567006'});assert.equal(inside.events[0].eventType,'quick_ctc');assert.equal(inside.events[0].metadata.elapsedCalendarDays,6);const outside=new VictoryExecutor({underwritingSubmittedAt:'2026-09-01T18:00:00Z'});await repository.syncVictoryEvents(outside,{loanId:'loan-3',eventType:'CLEAR_TO_CLOSE',occurredAt:'2026-09-10T18:00:00Z',displayLoanId:'17567007'});assert.equal(outside.events.length,0);const missing=new VictoryExecutor();await repository.syncVictoryEvents(missing,{loanId:'loan-4',eventType:'CLEAR_TO_CLOSE',occurredAt:'2026-09-03T18:00:00Z',displayLoanId:'17567008'});assert.equal(missing.events.length,0);assert.equal(victorySettings.quickCtcCalendarDays,7);assert.equal(quickCtcElapsedCalendarDays('2026-09-01T18:00:00Z','2026-09-08T18:00:00Z'),7);});
test('funding count and volume goal crossings create once, while existing totals do not backfill',async()=>{const executor=new VictoryExecutor({afterCount:30,afterVolume:15000000,goalCount:30,goalVolume:15000000}),repository=new PostgresAriveRepository(executor),before={year:2026,month:9,fundedCount:{actual:29,goal:30},fundedVolume:{actual:14900000,goal:15000000}};await repository.syncVictoryEvents(executor,{loanId:'loan-5',eventType:'LOAN_FUNDED',occurredAt:'2026-09-15T18:00:00Z',displayLoanId:'17567009',fundingBefore:before});await repository.syncVictoryEvents(executor,{loanId:'loan-5',eventType:'LOAN_FUNDED',occurredAt:'2026-09-15T18:00:00Z',displayLoanId:'17567009',fundingBefore:before});assert.deepEqual(executor.events.map(event=>event.eventType),['loan_funded','funding_count_goal_hit','funding_volume_goal_hit']);assert.equal(goalWasCrossed(30,31,30),false);assert.equal(goalWasCrossed(29,30,30),true);});
test('production victory API returns only persisted events and development preview never persists one',async()=>{const production=createHfnServer({environment:'production',store:{victoryEvents:async()=>({events:[]})}}),development=createHfnServer({environment:'development',store:{}});await new Promise(resolve=>production.listen(0,resolve));await new Promise(resolve=>development.listen(0,resolve));try{const live=await (await fetch(`http://127.0.0.1:${production.address().port}/api/victory-events?after=2026-09-15T00%3A00%3A00.000Z`)).json(),preview=await (await fetch(`http://127.0.0.1:${development.address().port}/api/development/victory-events/preview`)).json();assert.deepEqual(live,{events:[]});assert.equal(preview.event.displayLoanId,'PREVIEW-ONLY');}finally{await new Promise(resolve=>production.close(resolve));await new Promise(resolve=>development.close(resolve));}});
