import test from 'node:test';
import assert from 'node:assert/strict';
import { reconcileAriveMilestones } from '../src/domain/workflow-reconciliation.js';
import { reconciliationEvidence } from '../src/domain/workflow-reconciliation.js';
import { PostgresAriveRepository } from '../src/storage/postgres-arive.js';

function executor(open={}){const updates=[],history=[];return {updates,history,async query(sql,params=[]){if(sql.startsWith('select id,state')){const taskType=params[1];return {rows:open[taskType]?[{id:`${taskType}-id`,state:open[taskType],kpi_eligible:false}]:[]};}if(sql.startsWith('update workflow_tasks')){updates.push(params);return {rows:[]};}if(sql.startsWith('insert into workflow_task_history')){history.push(params);return {rows:[]};}throw new Error(`Unexpected query ${sql}`);}};}
function chainedExecutor(initial={}){const states=new Map(Object.entries(initial)),ids=new Map([...states.keys()].map(type=>[type,`${type}-id`])),types=new Map([...ids.entries()].map(([type,id])=>[id,type])),updates=[],history=[];return {states,updates,history,async query(sql,params=[]){if(sql.startsWith('select id,state,kpi_eligible')){const type=params[1],state=states.get(type);return {rows:state&&!["completed","cancelled","not_applicable"].includes(state)?[{id:ids.get(type),state,kpi_eligible:false}]:[]};}if(sql.startsWith('select id from workflow_tasks')){const type=params[1];return {rowCount:states.has(type)?1:0,rows:states.has(type)?[{id:ids.get(type)}]:[]};}if(sql.startsWith('select id,loan_id,task_type')){const type=types.get(params[0]);return {rows:type?[{id:params[0],loan_id:'loan-1',task_type:type,origin:'automatic',owner_role:'processor_assistant',owner_email:'assistant@hfn.test',owner_name:'Assistant',kpi_eligible:false,metadata:{}}]:[]};}if(sql.startsWith('update workflow_tasks')){const type=types.get(params[0]),state=sql.includes("state='cancelled'")?'cancelled':'completed';states.set(type,state);updates.push({taskType:type,completedAt:params[1]??null,state});return {rows:[]};}if(sql.includes('insert into workflow_tasks')){const [id,,type]=params;ids.set(type,id);types.set(id,type);if(!states.has(type))states.set(type,'waiting');return {rowCount:1,rows:[{id}]};}if(sql.startsWith('insert into workflow_task_history')){history.push(params);return {rows:[]};}throw new Error(`Unexpected query ${sql}`);}};}
test('authoritative ARIVE dates reconcile the matching open task with the actual timestamp',async()=>{const db=executor({request_insurance_eoi:'past_due',order_title_escrow:'blocked',order_appraisal:'waiting',closing_disclosure_sent:'action_required'}),dates={hoiOrderedDate:'2026-09-13T21:30:00Z',titleOrderedDate:'2026-09-12T21:30:00Z',appraisalOrderedDate:'2026-09-11T21:30:00Z',initialCDSentDate:'2026-09-14T21:30:00Z'};const result=await reconcileAriveMilestones(db,{loanId:'loan-1',milestoneDates:dates});assert.equal(result.length,4);assert.equal(db.updates.length,4);assert.deepEqual(db.updates.map(row=>row[1]),[dates.appraisalOrderedDate,dates.titleOrderedDate,dates.hoiOrderedDate,dates.initialCDSentDate]);assert.equal(db.history.length,4);assert.equal(JSON.stringify(db.history).includes('borrower'),false);});
test('reconciliation dry-run reports candidates without writes',async()=>{const db=executor({request_insurance_eoi:'past_due',order_title_escrow:'blocked'}),result=await reconcileAriveMilestones(db,{loanId:'loan-1',milestoneDates:{hoiOrderedDate:'2026-09-13T21:30:00Z',titleOrderedDate:'2026-09-13T21:30:00Z'},dryRun:true});assert.equal(result.length,2);assert.equal(db.updates.length,0);assert.equal(db.history.length,0);});
test('ORDERED tracker status and date reconcile only when preferred key date is absent',()=>{const tracker={hoiStatus:' ordered ',hoiTrackerDate:'2026-09-13T21:30:00Z',titleStatus:'ORDERED',titleTrackerDate:'2026-09-12T21:30:00Z',appraisalStatus:'received',appraisalTrackerDate:'2026-09-11T21:30:00Z'},evidence=reconciliationEvidence({},tracker);assert.equal(evidence.find(item=>item.taskType==='request_insurance_eoi').completedAt,tracker.hoiTrackerDate);assert.equal(evidence.find(item=>item.taskType==='order_title_escrow').completedAt,tracker.titleTrackerDate);assert.equal(evidence.find(item=>item.taskType==='order_appraisal').completedAt,null);const preferred=reconciliationEvidence({hoiOrderedDate:'2026-09-10T21:30:00Z'},tracker).find(item=>item.taskType==='request_insurance_eoi');assert.equal(preferred.completedAt,'2026-09-10T21:30:00Z');assert.equal(preferred.evidence,'key_date');});
test('received key dates close only their separate third-party follow-up tasks',()=>{const evidence=reconciliationEvidence({appraisalReceivedDate:'2026-09-15T21:30:00Z',titleReceivedDate:'2026-09-15T21:30:00Z',hoiReceivedDate:'2026-09-15T21:30:00Z'});assert.deepEqual(evidence.filter(item=>item.completedAt).map(item=>item.taskType),['appraisal_follow_up','title_follow_up','insurance_follow_up']);});
test('title received key date completes only the title follow-up',()=>{const at='2026-09-15T21:30:00Z',evidence=reconciliationEvidence({titleReceivedDate:at},{});assert.equal(evidence.find(item=>item.taskType==='title_follow_up').completedAt,at);assert.equal(evidence.find(item=>item.taskType==='title_follow_up').evidence,'key_date');assert.equal(evidence.find(item=>item.taskType==='order_title_escrow').completedAt,null);});
test('trimmed case-insensitive RECEIVED tracker status closes only title follow-up with title date',()=>{for(const status of ['RECEIVED',' received ','ReCeIvEd']){const at='2026-09-15T21:30:00Z',evidence=reconciliationEvidence({},{titleStatus:status,titleTrackerDate:at});const followUp=evidence.find(item=>item.taskType==='title_follow_up'),initial=evidence.find(item=>item.taskType==='order_title_escrow');assert.equal(followUp.completedAt,at);assert.equal(followUp.evidence,'tracker_received_date');assert.equal(initial.completedAt,null);}});
test('title date alone and non-received status cannot close title follow-up',()=>{for(const status of [null,'ORDERED','IN REVIEW','RECEIVED_PENDING']){const evidence=reconciliationEvidence({},{titleStatus:status,titleTrackerDate:'2026-09-15T21:30:00Z'});assert.equal(evidence.find(item=>item.taskType==='title_follow_up').completedAt,null);}});
test('ORDERED tracker evidence closes only the initial title order task',()=>{const evidence=reconciliationEvidence({},{titleStatus:' ORDERED ',titleTrackerDate:'2026-09-15T21:30:00Z'});assert.equal(evidence.find(item=>item.taskType==='order_title_escrow').completedAt,'2026-09-15T21:30:00Z');assert.equal(evidence.find(item=>item.taskType==='title_follow_up').completedAt,null);});
test('received fallback reconciliation persists titleDate, retains KPI eligibility, and remains PII-safe',async()=>{const db=executor({title_follow_up:'waiting'}),at='2026-09-15T21:30:00Z';const result=await reconcileAriveMilestones(db,{loanId:'loan-1',milestoneDates:{},trackerContext:{titleStatus:'received',titleTrackerDate:at}});assert.equal(result.length,1);assert.deepEqual(result[0],{taskId:'title_follow_up-id',taskType:'title_follow_up',completedAt:at,evidence:'tracker_received_date'});assert.equal(db.updates[0][1],at);assert.equal(JSON.stringify(db.history).includes('borrower'),false);assert.equal(JSON.stringify(db.history).includes('kpi_eligible'),false);});
test('same-event ordered and received ARIVE evidence closes newly-created vendor follow-ups immediately',async()=>{const db=chainedExecutor({order_appraisal:'action_required',order_title_escrow:'action_required',request_insurance_eoi:'action_required'}),dates={appraisalOrderedDate:'2026-09-08T18:00:00Z',appraisalReceivedDate:'2026-09-10T18:00:00Z',titleOrderedDate:'2026-09-08T18:00:00Z',titleReceivedDate:'2026-09-10T18:00:00Z',hoiOrderedDate:'2026-09-08T18:00:00Z',hoiReceivedDate:'2026-09-10T18:00:00Z'},result=await new PostgresAriveRepository({}).reconcileWorkflowMilestones(db,{loanId:'loan-1',milestoneDates:dates});assert.deepEqual(result.map(item=>item.taskType),['order_appraisal','order_title_escrow','request_insurance_eoi','appraisal_follow_up','title_follow_up','insurance_follow_up']);assert.deepEqual(db.updates.filter(item=>item.taskType.endsWith('_follow_up')).map(item=>item.completedAt),[dates.appraisalReceivedDate,dates.titleReceivedDate,dates.hoiReceivedDate]);assert.ok([...db.states.values()].every(state=>state==='completed'));assert.equal(result.some(item=>item.taskType.includes('payoff')),false);});
test('authoritative receipt without an ordered timestamp supersedes only the matching open initial vendor task',async()=>{for(const [initialTaskType,receivedKey] of [['order_title_escrow','titleReceivedDate'],['order_appraisal','appraisalReceivedDate'],['request_insurance_eoi','hoiReceivedDate']]){const db=chainedExecutor({[initialTaskType]:'past_due'}),at='2026-09-15T21:30:00Z',result=await new PostgresAriveRepository({}).reconcileWorkflowMilestones(db,{loanId:'loan-1',milestoneDates:{[receivedKey]:at}});assert.deepEqual(result,[{taskId:`${initialTaskType}-id`,taskType:initialTaskType,action:'arive_final_milestone_superseded_initial_task',authoritativeAt:at,evidence:'key_date',orderedTimestamp:'unknown'}]);assert.equal(db.states.get(initialTaskType),'cancelled');assert.deepEqual(db.updates,[{taskType:initialTaskType,completedAt:null,state:'cancelled'}]);assert.equal([...db.states.keys()].some(type=>type.endsWith('_follow_up')),false);const metadata=db.history[0].at(-1);assert.deepEqual(metadata,{finalMilestone:initialTaskType==='order_title_escrow'?'title_received':initialTaskType==='order_appraisal'?'appraisal_received':'hoi_received',authoritativeAt:at,evidence:'key_date',orderedTimestamp:'unknown',source:'arive'});assert.equal(JSON.stringify(db.history).includes('borrower'),false);}});
test('Title RECEIVED tracker evidence also supersedes a missing Title order without inventing a date',async()=>{const db=chainedExecutor({order_title_escrow:'past_due'}),at='2026-09-15T21:30:00Z',result=await new PostgresAriveRepository({}).reconcileWorkflowMilestones(db,{loanId:'loan-1',trackerContext:{titleStatus:' received ',titleTrackerDate:at}});assert.equal(result[0].action,'arive_final_milestone_superseded_initial_task');assert.equal(result[0].authoritativeAt,at);assert.equal(db.states.get('order_title_escrow'),'cancelled');assert.equal(db.updates[0].completedAt,null);});
test('missing received evidence does not shortcut an initial vendor task',async()=>{const db=chainedExecutor({order_title_escrow:'past_due'}),result=await new PostgresAriveRepository({}).reconcileWorkflowMilestones(db,{loanId:'loan-1',milestoneDates:{}});assert.deepEqual(result,[]);assert.equal(db.states.get('order_title_escrow'),'past_due');assert.deepEqual(db.updates,[]);});
