import test from 'node:test';
import assert from 'node:assert/strict';
import { businessDeadline, checklistComplete, createWorkflowTask, nextFollowUpAt, recordFollowUp, safeWorkflowMetadata, transitionTask } from '../src/domain/workflow-engine.js';
import { definitionsForTrigger } from '../src/domain/workflow-definitions.js';

const calendar={businessStart:{hour:8,minute:30},businessEnd:{hour:17,minute:0},workdays:[1,2,3,4,5],holidays:[]};
const setup=definitionsForTrigger('LOAN_SETUP')[0];

test('workflow definitions automatically describe LOAN_SETUP ownership and deadline',()=>{const task=createWorkflowTask({id:'task-1',loanId:'loan-1',definition:setup,createdAt:'2026-09-11T23:00:00.000Z',ownerEmail:'assistant@hfn.test',kpiEligible:true,calendar});assert.equal(task.ownerRole,'processor_assistant');assert.equal(task.state,'action_required');assert.equal(task.dueAt,'2026-09-14T23:00:00.000Z');assert.equal(task.kpiEligible,true);});
test('workflow deadlines and follow-ups use Pacific business days over weekends and holidays',()=>{assert.equal(businessDeadline('2026-09-11T23:00:00.000Z',1,calendar),'2026-09-14T23:00:00.000Z');assert.equal(businessDeadline('2026-09-11T23:00:00.000Z',1,{...calendar,holidays:['2026-09-14']}),'2026-09-15T23:00:00.000Z');assert.equal(nextFollowUpAt('2026-09-10T17:00:00.000Z',2,calendar),'2026-09-14T17:00:00.000Z');});
test('waiting task follow-ups record history-ready timestamps and recurrence',()=>{const task={id:'task-2',state:'waiting',followUpCadenceBusinessDays:1,followUpCount:0};const updated=recordFollowUp(task,{at:'2026-09-11T23:00:00.000Z',calendar,actorEmail:'assistant@hfn.test'});assert.equal(updated.state,'waiting');assert.equal(updated.followUpCount,1);assert.equal(updated.nextFollowUpAt,'2026-09-14T23:00:00.000Z');});
test('insurance follow-up uses the defined initial and repeat business cadences',()=>{const first=recordFollowUp({taskType:'request_insurance_eoi',followUpCadenceBusinessDays:3,followUpCount:0},{at:'2026-09-11T23:00:00.000Z',calendar}),repeat=recordFollowUp({...first,followUpCount:1},{at:'2026-09-16T23:00:00.000Z',calendar});assert.equal(first.nextFollowUpAt,'2026-09-16T23:00:00.000Z');assert.equal(repeat.nextFollowUpAt,'2026-09-18T23:00:00.000Z');assert.equal(repeat.followUpCount,2);});
test('tasks without a cadence cannot invent a follow-up schedule',()=>{assert.throws(()=>recordFollowUp({taskType:'manual_operational_task',followUpCount:0},{at:'2026-09-11T23:00:00.000Z',calendar}),/no follow-up cadence/);});
test('follow-up history metadata keeps operational fields and excludes borrower content',()=>{const metadata=safeWorkflowMetadata({previousState:'action_required',resultingState:'waiting',lastFollowUpAt:'2026-09-11T23:00:00.000Z',nextFollowUpAt:'2026-09-14T23:00:00.000Z',followUpCount:1,waitingOn:'insurance_agent',borrowerName:'Jane Doe',note:'borrower phone 555-0100'});assert.deepEqual(metadata,{previousState:'action_required',resultingState:'waiting',lastFollowUpAt:'2026-09-11T23:00:00.000Z',nextFollowUpAt:'2026-09-14T23:00:00.000Z',followUpCount:1,waitingOn:'insurance_agent'});});
test('manual and conditional tasks use the shared model and safe states',()=>{const definition={type:'appraisal_correction',title:'Request appraisal correction',ownerRole:'processor_assistant',businessDays:2};const task=createWorkflowTask({id:'task-3',loanId:'loan-1',definition,createdAt:'2026-09-10T17:00:00.000Z',origin:'conditional',kpiEligible:false,calendar,metadata:{conditionReference:'UW appraisal correction',borrowerName:'not permitted'}});assert.equal(task.origin,'conditional');assert.deepEqual(task.metadata,{conditionReference:'UW appraisal correction'});const blocked=transitionTask(task,{state:'blocked',at:'2026-09-10T18:00:00.000Z',reason:'Awaiting appraiser',actorEmail:'assistant@hfn.test'});assert.equal(blocked.blockedReason,'Awaiting appraiser');assert.equal(blocked.kpiEligible,false);});
test('checklists require every applicable item to complete or be explicitly N/A',()=>{assert.equal(checklistComplete([{state:'completed'},{state:'not_applicable'}]),true);assert.equal(checklistComplete([{state:'completed'},{state:'action_required'}]),false);assert.equal(checklistComplete([]),false);});
test('funding can cancel remaining operational tasks without erasing their history or changing KPI eligibility',()=>{const task={id:'task-4',state:'waiting',kpiEligible:false};const cancelled=transitionTask(task,{state:'cancelled',at:'2026-09-12T17:00:00.000Z'});assert.equal(cancelled.state,'cancelled');assert.equal(cancelled.kpiEligible,false);});
test('historical in-flight workflow tasks remain operational but are not retroactive KPI failures',()=>{const task=createWorkflowTask({id:'task-5',loanId:'loan-1',definition:setup,createdAt:'2026-09-10T17:00:00.000Z',kpiEligible:false,calendar});const pastDue=transitionTask(task,{state:'past_due',at:'2026-09-12T17:00:00.000Z'});assert.equal(pastDue.state,'past_due');assert.equal(pastDue.kpiEligible,false);});
