import test from 'node:test';
import assert from 'node:assert/strict';
import { planHydratedWorkflow } from '../src/domain/workflow-hydration.js';
const owners={processor:{email:'processor@hfn.test',name:'Processor'},assistant:{email:'assistant@hfn.test',name:'Assistant'},now:'2026-09-15T18:00:00.000Z'};
test('hydration creates current UW work only, all KPI-ineligible',()=>{const plan=planHydratedWorkflow({stage:'UNDERWRITING_SUBMITTED',purpose:'Rate/Term Refinance',milestoneDates:{},...owners});assert.deepEqual(plan.tasks.map(task=>task.type),['order_appraisal','order_title_escrow','request_insurance_eoi','order_payoff']);assert.ok(plan.tasks.every(task=>task.kpiEligible===false));assert.ok(plan.tasks.every(task=>!task.completedAt&&!task.lastFollowUpAt));});
test('hydrated Payoff is limited to explicit refinance purposes',()=>{for(const purpose of ['refinance','Cash-Out Refinance','rate/term refinance'])assert.ok(planHydratedWorkflow({stage:'UNDERWRITING_SUBMITTED',purpose,...owners}).tasks.some(task=>task.type==='order_payoff'));for(const purpose of ['purchase','HELOC','second mortgage','commercial',null])assert.ok(!planHydratedWorkflow({stage:'UNDERWRITING_SUBMITTED',purpose,...owners}).tasks.some(task=>task.type==='order_payoff'));});
test('hydration uses proven dates to skip historical ordering and create only current CD work',()=>{const plan=planHydratedWorkflow({stage:'UNDERWRITING_SUBMITTED',purpose:'purchase',milestoneDates:{appraisalReceivedDate:'2026-09-10T18:00:00Z',titleReceivedDate:'2026-09-10T18:00:00Z',hoiReceivedDate:'2026-09-10T18:00:00Z'},...owners});assert.deepEqual(plan.tasks.map(task=>task.type),['closing_disclosure_sent']);});
test('terminal and pre-processing loans receive no hydrated work',()=>{for(const stage of ['LOAN_FUNDED','APPLICATION_INTAKE','ADVERSE','SUSPENDED'])assert.equal(planHydratedWorkflow({stage,...owners}).tasks.length,0);});
test('downstream stages infer only current operational work',()=>{assert.deepEqual(planHydratedWorkflow({stage:'CLEAR_TO_CLOSE',...owners}).tasks.map(task=>task.type),['request_loan_documents','ctc_closing_readiness']);assert.deepEqual(planHydratedWorkflow({stage:'DOCS_SIGNED',...owners}).tasks.map(task=>task.type),['clear_funding_requirements']);});
