import test from 'node:test';
import assert from 'node:assert/strict';
import { createHfnServer } from '../server.mjs';
async function withServer(employee,run){const calls=[],store={myWorkQueue:async input=>({viewer:{email:input.employee.email,role:input.employee.role},tasks:[]}),mutateWorkflowTask:async input=>{calls.push(input);return {ok:true};}},auth={session:async()=>employee},server=createHfnServer({store,auth,environment:'production'});await new Promise(resolve=>server.listen(0,resolve));try{await run(`http://127.0.0.1:${server.address().port}`,calls);}finally{await new Promise(resolve=>server.close(resolve));}}
test('unauthenticated workflow mutation is denied',async()=>{const server=createHfnServer({store:{mutateWorkflowTask:async()=>({ok:true})},environment:'production'});await new Promise(resolve=>server.listen(0,resolve));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/api/my-work/tasks/task-1/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"action":"complete"}'})).status,401);}finally{await new Promise(resolve=>server.close(resolve));}});
test('task action identity comes only from the authenticated employee',async()=>withServer({email:'joshua@hfn.test',role:'processor_assistant'},async(base,calls)=>{const response=await fetch(`${base}/api/my-work/tasks/task-1/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'follow_up',ownerEmail:'other@hfn.test'})});assert.equal(response.status,200);assert.equal(calls[0].employee.email,'joshua@hfn.test');assert.equal(calls[0].action,'follow_up');assert.equal(calls[0].ownerEmail,undefined);}));

test('processor review outcomes use the authenticated employee and the dedicated server-side mutation path',async()=>{const calls=[],employee={email:'processor@hfn.test',role:'processor'},store={mutateProcessorReview:async input=>{calls.push(input);return {ok:true};}},auth={session:async()=>employee},server=createHfnServer({store,auth,environment:'production'});await new Promise(resolve=>server.listen(0,resolve));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/my-work/tasks/review-1/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'review_issue_found',note:'Operational exception',ownerEmail:'spoofed'})});assert.equal(response.status,200);assert.deepEqual(calls,[{employee,taskId:'review-1',action:'review_issue_found',note:'Operational exception'}]);}finally{await new Promise(resolve=>server.close(resolve));}});

test('post-CTC manual actions use authenticated, dedicated task endpoints',async()=>{const calls=[],employee={email:'processor@hfn.test',role:'processor'},store={markDocsSentToNotary:async input=>{calls.push(['sent',input]);return {ok:true};},markDocsSigned:async input=>{calls.push(['signed',input]);return {ok:true};}},auth={session:async()=>employee},server=createHfnServer({store,auth,environment:'production'});await new Promise(resolve=>server.listen(0,resolve));try{for(const path of ['docs-sent-to-notary','docs-signed'])assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/api/my-work/tasks/task-1/${path}`,{method:'POST'})).status,200);assert.deepEqual(calls.map(([kind])=>kind),['sent','signed']);assert.ok(calls.every(([,input])=>input.employee.email===employee.email&&input.taskId==='task-1'));}finally{await new Promise(resolve=>server.close(resolve));}});

test('checklist endpoint preserves the authenticated employee and sends only item state',async()=>{const calls=[],employee={email:'joshua@hfn.test',role:'processor_assistant'},store={mutateWorkflowChecklist:async input=>{calls.push(input);return {ok:true};}},auth={session:async()=>employee},server=createHfnServer({store,auth,environment:'production'});await new Promise(resolve=>server.listen(0,resolve));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/my-work/tasks/task-1/checklist-items/item-1`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:'completed',employee:'spoofed'})});assert.equal(response.status,200);assert.deepEqual(calls[0],{employee,taskId:'task-1',checklistItemId:'item-1',checklistState:'completed'});}finally{await new Promise(resolve=>server.close(resolve));}});
