-- PostgreSQL-oriented normalized internal data layer. No frontend consumes raw ARIVE payloads.
create table users (id uuid primary key, display_name text not null, role text not null check (role in ('processor','assistant','loan_officer','manager')), active boolean not null default true);
create table loans (id uuid primary key, arive_system_guid text unique not null, arive_display_loan_id text unique, loan_number text unique, purpose text, mortgage_type text, city text, state text, current_stage text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table loan_stage_events (id uuid primary key, loan_id uuid not null references loans, event_type text not null, occurred_at timestamptz not null, received_at timestamptz not null, source text not null, source_event_id text, metadata jsonb not null default '{}', unique(source, source_event_id), unique(loan_id, event_type, occurred_at, source));
create table processor_assignments (id uuid primary key, loan_id uuid not null references loans, user_id uuid not null references users, assignment_role text not null check (assignment_role in ('processor','assistant')), assigned_at timestamptz not null, unassigned_at timestamptz);
create table assistant_tasks (id uuid primary key, loan_id uuid not null references loans, assistant_id uuid references users, task_type text not null check (task_type in ('appraisal','title','insurance','payoff','post_approval_orders')), applicable_at timestamptz not null, due_at timestamptz, completed_at timestamptz, status text not null, created_from_event_id uuid references loan_stage_events, unique(loan_id, task_type));
create table sla_rules (id uuid primary key, metric_key text unique not null, duration_value numeric not null, duration_unit text not null, config jsonb not null default '{}', active boolean not null default true);
create table sla_measurements (id uuid primary key, loan_id uuid not null references loans, rule_id uuid not null references sla_rules, start_event_id uuid references loan_stage_events, completed_event_id uuid references loan_stage_events, due_at timestamptz not null, evaluated_at timestamptz not null, state text not null);
create table manual_events (id uuid primary key, loan_id uuid not null references loans, event_type text not null check (event_type in ('conditions_review_started','conditions_review_completed','loan_setup_completed')), occurred_at timestamptz not null, entered_by uuid references users, notes text);
-- Persist a redacted operational audit representation and SHA-256 fingerprint; never persist raw borrower payloads.
create table inbound_events (id uuid primary key, source text not null, external_id text, idempotency_key text not null, payload_hash char(64) not null, received_at timestamptz not null, payload jsonb not null, processing_status text not null default 'received' check (processing_status in ('received','processed','failed','duplicate')), failure_reason text, processed_at timestamptz);
create table webhook_idempotency (source text not null, idempotency_key text not null, first_audit_id uuid not null references inbound_events, primary key (source,idempotency_key));
create table assistant_task_bundles (id uuid primary key, loan_id uuid not null references loans, bundle_type text not null check (bundle_type='post_approval_orders'), created_from_event_id uuid references loan_stage_events, created_at timestamptz not null, unique(loan_id,bundle_type));
create table business_calendars (id uuid primary key, name text unique not null, time_zone text not null default 'America/Los_Angeles', business_start time not null default '08:30', business_end time not null default '17:00', workdays smallint[] not null default array[1,2,3,4,5]);
create table calendar_holidays (id uuid primary key, calendar_id uuid not null references business_calendars, holiday_date date not null, name text, unique(calendar_id, holiday_date));
create table assistant_performance_config (id uuid primary key, completion_weight numeric not null default .40, sla_weight numeric not null default .30, turnaround_weight numeric not null default .20, backlog_weight numeric not null default .10, check (completion_weight + sla_weight + turnaround_weight + backlog_weight = 1));
