import { randomUUID } from 'node:crypto';
import { assistantMilestones } from '../domain/events.js';
import { defaultCalendar, dueAt, setHfnBusinessCalendar } from '../domain/sla.js';
import { normalizeArivePayload, payloadFingerprint, payloadIdempotencyKey, redactedAuditPayload, supportedEventType } from '../integrations/arive.js';
import { buildLiveDashboard } from '../domain/dashboard.js';
import { fundingGoalSummary } from '../domain/funding-goals.js';
import { fundingAggregateSql } from './funding-aggregate.js';
const pacificYearMonth=(now=new Date())=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'numeric'}).formatToParts(now);return {year:Number(parts.find(part=>part.type==='year').value),month:Number(parts.find(part=>part.type==='month').value)};};
export class PostgresAriveRepository {
  constructor(pool){this.pool=pool;this.calendar=defaultCalendar;}
  async initialize(){const {readFile}=await import('node:fs/promises');await this.pool.query('create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now())');for(const migration of [['001_initial','../../db/schema.sql'],['002_assistant_milestones','../../db/002_assistant_milestones.sql'],['003_remove_payoff_milestones','../../db/003_remove_payoff_milestones.sql'],['004_repair_processor_assistant_role','../../db/004_repair_processor_assistant_role.sql'],['005_processing_pipeline_eligibility','../../db/005_processing_pipeline_eligibility.sql'],['006_bootstrap_in_flight_processing_eligibility','../../db/006_bootstrap_in_flight_processing_eligibility.sql'],['007_protect_kpis_from_preexisting_history','../../db/007_protect_kpis_from_preexisting_history.sql'],['008_correct_sla_ownership','../../db/008_correct_sla_ownership.sql'],['009_monthly_funding_goals','../../db/009_monthly_funding_goals.sql'],['010_historical_funding_corrections','../../db/010_historical_funding_corrections.sql'],['011_closing_disclosure_sent','../../db/011_closing_disclosure_sent.sql']]){const applied=await this.pool.query('select name from schema_migrations where name=$1',[migration[0]]);if(applied.rowCount)continue;const client=await this.pool.connect();try{await client.query('begin');await client.query(await readFile(new URL(migration[1],import.meta.url),'utf8'));await client.query('insert into schema_migrations (name) values ($1)',[migration[0]]);await client.query('commit');}catch(error){await client.query('rollback');throw error;}finally{client.release();}}const holidays=await this.pool.query(`select h.holiday_date::text holiday_date from calendar_holidays h join business_calendars c on c.id=h.calendar_id where c.name='HFN' order by h.holiday_date`);this.calendar={...defaultCalendar,holidays:holidays.rows.map(row=>row.holiday_date)};setHfnBusinessCalendar(this.calendar);await this.repairAssistantDeadlines();await this.repairClosingDisclosureTasks();}
  assistantDeadline(submittedAt,milestone){return dueAt(submittedAt,{kind:'businessHours',value:milestone.businessDays*8.5},this.calendar).toISOString();}
  async repairAssistantDeadlines(){const tasks=await this.pool.query(`select t.id,t.task_type,e.occurred_at from assistant_tasks t join loan_stage_events e on e.id=t.created_from_event_id where e.event_type='UNDERWRITING_SUBMITTED'`);for(const task of tasks.rows){const milestone=assistantMilestones.find(item=>item.type===task.task_type);if(!milestone)continue;const dueAt=this.assistantDeadline(task.occurred_at,milestone);await this.pool.query('update assistant_tasks set due_at=$2 where id=$1 and due_at is distinct from $2',[task.id,dueAt]);}}
  async syncClosingDisclosureTask(executor,loanId,createdFromEventId,milestoneDates){const applicableAt=milestoneDates.appraisalReceivedDate,completedAt=milestoneDates.initialCDSentDate??null;if(!applicableAt){if(completedAt)await executor.query(`update assistant_tasks set completed_at=coalesce(completed_at,$2),status=case when coalesce(completed_at,$2)<=due_at then 'completed_within_sla' else 'completed_late' end where loan_id=$1 and task_type='closing_disclosure_sent'`,[loanId,completedAt]);return 0;}const dueAtValue=dueAt(applicableAt,{kind:'businessHours',value:17},this.calendar).toISOString(),status=completedAt?(new Date(completedAt)<=new Date(dueAtValue)?'completed_within_sla':'completed_late'):'open';const result=await executor.query(`insert into assistant_tasks (id,loan_id,task_type,applicable_at,due_at,completed_at,status,created_from_event_id) values ($1,$2,'closing_disclosure_sent',$3,$4,$5,$6,$7) on conflict (loan_id,task_type) do update set completed_at=coalesce(assistant_tasks.completed_at,excluded.completed_at),status=case when coalesce(assistant_tasks.completed_at,excluded.completed_at) is null then assistant_tasks.status when coalesce(assistant_tasks.completed_at,excluded.completed_at)<=assistant_tasks.due_at then 'completed_within_sla' else 'completed_late' end returning (xmax=0) inserted`,[randomUUID(),loanId,applicableAt,dueAtValue,completedAt,status,createdFromEventId]);return result.rows?.[0]?.inserted?1:0;}
  async repairClosingDisclosureTasks(){const snapshots=await this.pool.query(`select l.id loan_id,nullif(i.payload->'milestoneDates'->>'appraisalReceivedDate','') appraisal_received_date,nullif(i.payload->'milestoneDates'->>'initialCDSentDate','') initial_cd_sent_date from loans l join lateral (select payload from inbound_events i where i.source='zapier-arive' and i.payload->>'ariveSystemGuid'=l.arive_system_guid order by i.received_at desc,i.id desc limit 1) i on true`);for(const snapshot of snapshots.rows)await this.syncClosingDisclosureTask(this.pool,snapshot.loan_id,null,{appraisalReceivedDate:snapshot.appraisal_received_date,initialCDSentDate:snapshot.initial_cd_sent_date});}
  async receive(payload,receivedAt=new Date().toISOString()) {
    const client=await this.pool.connect(),id=randomUUID(),key=payloadIdempotencyKey(payload);
    try {
      await client.query('BEGIN');
      await client.query('insert into inbound_events (id,source,external_id,idempotency_key,payload_hash,received_at,payload,processing_status) values ($1,$2,$3,$4,$5,$6,$7,$8)',[id,'zapier-arive',key,key,payloadFingerprint(payload),receivedAt,redactedAuditPayload(payload,receivedAt),'received']);
      const claim=await client.query('insert into webhook_idempotency (source,idempotency_key,first_audit_id) values ($1,$2,$3) on conflict do nothing returning idempotency_key',['zapier-arive',key,id]);
      if(!claim.rowCount){await client.query("update inbound_events set processing_status='duplicate',processed_at=$2 where id=$1",[id,receivedAt]);await client.query('COMMIT');return {ok:true,outcome:'duplicate',tasksCreated:0};}
      const loan=normalizeArivePayload(payload,receivedAt);
      if(!loan.systemGuid)return await this.fail(client,id,receivedAt,'Missing ARIVE System GUID');
      await client.query(`insert into loans (id,arive_system_guid,arive_display_loan_id,loan_number,purpose,mortgage_type,city,state,current_stage,created_at,updated_at) values ($1,$2,$3,$3,$4,$5,$6,$7,$8,$9,$9) on conflict (arive_system_guid) do update set arive_display_loan_id=excluded.arive_display_loan_id,purpose=excluded.purpose,mortgage_type=excluded.mortgage_type,city=excluded.city,state=excluded.state,current_stage=excluded.current_stage,updated_at=excluded.updated_at`,[randomUUID(),loan.systemGuid,loan.displayLoanId,loan.purpose,loan.mortgageType,loan.city,loan.state,loan.currentStatus??'UNKNOWN',receivedAt]);
      const row=await client.query('select id from loans where arive_system_guid=$1',[loan.systemGuid]),loanId=row.rows[0].id,eventType=supportedEventType(loan.currentStatus);
      if(!eventType||!loan.statusAt){const tasksCreated=await this.syncClosingDisclosureTask(client,loanId,null,loan.milestoneDates);await client.query("update inbound_events set processing_status='processed',failure_reason=$2,processed_at=$3 where id=$1",[id,eventType?'Missing Current Loan Status Date; no milestone created':'No supported status event',receivedAt]);await client.query('COMMIT');return {ok:true,outcome:'accepted-no-event',tasksCreated};}
      const eventId=randomUUID();
      await client.query('insert into loan_stage_events (id,loan_id,event_type,occurred_at,received_at,source,source_event_id,metadata) values ($1,$2,$3,$4,$5,$6,$7,$8) on conflict do nothing',[eventId,loanId,eventType,loan.statusAt,receivedAt,'zapier-arive',key,{ariveDisplayLoanId:loan.displayLoanId,processor:loan.processor,processorEmail:loan.processorEmail,assistant:loan.assistant,assistantEmail:loan.assistantEmail,assignmentException:loan.assistantException,loanTeamRoles:loan.teamUsers}]);
      let tasksCreated=0;
      if(eventType==='UNDERWRITING_SUBMITTED')for(const milestone of assistantMilestones){const completedAt=loan.milestoneDates[milestone.completionKey]??null,deadline=dueAt(loan.statusAt,{kind:'businessHours',value:milestone.businessDays*8.5},this.calendar).toISOString(),created=await client.query(`insert into assistant_tasks (id,loan_id,task_type,applicable_at,due_at,completed_at,status,created_from_event_id) values ($1,$2,$3,$4,$5,$6,$7,$8) on conflict (loan_id,task_type) do nothing returning id`,[randomUUID(),loanId,milestone.type,loan.statusAt,deadline,completedAt,completedAt?'completed':'open',eventId]);tasksCreated+=created.rowCount;}
      tasksCreated+=await this.syncClosingDisclosureTask(client,loanId,eventId,loan.milestoneDates);
      await client.query("update inbound_events set processing_status='processed',processed_at=$2 where id=$1",[id,receivedAt]);await client.query('COMMIT');return {ok:true,outcome:'processed',tasksCreated};
    } catch(error){await client.query('ROLLBACK');throw error;} finally {client.release();}
  }
  async fail(client,id,receivedAt,reason){await client.query("update inbound_events set processing_status='failed',failure_reason=$2,processed_at=$3 where id=$1",[id,reason,receivedAt]);await client.query('COMMIT');return {ok:false,outcome:'failed',error:reason};}
  async listLoans(search=''){const term=`%${search}%`;const result=await this.pool.query(`select l.id,l.arive_display_loan_id,l.current_stage,l.city,l.state,coalesce(e.metadata->>'processor','Unassigned') processor,coalesce(e.metadata->>'assistant','Unassigned') assistant,(select task_type from assistant_tasks t where t.loan_id=l.id and t.completed_at is null order by t.due_at asc nulls last limit 1) next_milestone,(select due_at from assistant_tasks t where t.loan_id=l.id and t.completed_at is null order by t.due_at asc nulls last limit 1) next_due_at from loans l left join lateral (select metadata from loan_stage_events where loan_id=l.id order by occurred_at desc,received_at desc limit 1) e on true where coalesce(l.arive_display_loan_id,'') ilike $1 or coalesce(l.current_stage,'') ilike $1 or coalesce(l.city,'') ilike $1 or coalesce(l.state,'') ilike $1 or coalesce(e.metadata->>'processor','') ilike $1 or coalesce(e.metadata->>'assistant','') ilike $1 order by l.updated_at desc limit 250`,[term]);return {source:'live',loans:result.rows.map(row=>this.safeLoanRow(row))};}
  safeLoanRow(row){const due=row.next_due_at?new Date(row.next_due_at):null,now=new Date();const slaStatus=!due?'On Track':due<now?'Breached':due-now<.2*(due-new Date(now.getTime()-8.5*3600000))?'Due Soon':'On Track';return {loanKey:row.id,displayLoanId:row.arive_display_loan_id??'—',processor:row.processor,assistant:row.assistant,currentStage:row.current_stage,cityState:[row.city,row.state].filter(Boolean).join(', ')||'—',nextMilestone:row.next_milestone?.replaceAll('_',' ')??'—',slaStatus};}
  async loanDetail(loanKey){const loan=await this.pool.query(`select l.id,l.arive_display_loan_id,l.current_stage,l.city,l.state,coalesce(e.metadata->>'processor','Unassigned') processor,coalesce(e.metadata->>'assistant','Unassigned') assistant from loans l left join lateral (select metadata from loan_stage_events where loan_id=l.id order by occurred_at desc,received_at desc limit 1) e on true where l.id=$1`,[loanKey]);if(!loan.rowCount)return null;const tasks=await this.pool.query(`select task_type,due_at,completed_at,status from assistant_tasks where loan_id=$1 order by due_at asc`,[loanKey]),processorSlas=await this.pool.query(`select r.metric_key,m.due_at,m.state from sla_measurements m join sla_rules r on r.id=m.rule_id where m.loan_id=$1 order by m.due_at asc`,[loanKey]);const detail=this.safeLoanRow(loan.rows[0]);return {...detail,processorSlas:processorSlas.rows.map(item=>({name:item.metric_key.replaceAll('_',' '),dueAt:item.due_at,status:item.state})),milestones:tasks.rows.map(task=>({name:task.task_type.replaceAll('_',' '),dueAt:task.due_at,completedAt:task.completed_at,status:task.completed_at?'Completed':new Date(task.due_at)<new Date()?'Breached':new Date(task.due_at)-new Date()<8.5*3600000?'Due Soon':'On Track'}))};}
  async fundingAggregate(year,month){const result=await this.pool.query(fundingAggregateSql,[year,month]);const row=result.rows[0]??{count:0,volume:0,missingAmountCount:0};return {count:Number(row.count),volume:Number(row.volume),missingAmountCount:Number(row.missingAmountCount)};}
  async fundingSummary(year,month){const [goal,actuals]=await Promise.all([this.pool.query('select funded_loan_goal "fundedLoanGoal",funded_volume_goal "fundedVolumeGoal" from monthly_funding_goals where year=$1 and month=$2',[year,month]),this.fundingAggregate(year,month)]);return fundingGoalSummary({year,month,goal:goal.rows[0]??null,actualCount:actuals.count,actualVolume:actuals.volume,missingAmountCount:actuals.missingAmountCount});}
  async monthlyFundingGoal(year,month){if(year===undefined||month===undefined)({year,month}=pacificYearMonth());return this.fundingSummary(year,month);}
  async saveMonthlyFundingGoal({year,month,fundedLoanGoal,fundedVolumeGoal}){if(!Number.isInteger(year)||!Number.isInteger(month)||month<1||month>12||!Number.isInteger(fundedLoanGoal)||fundedLoanGoal<=0||!Number.isFinite(fundedVolumeGoal)||fundedVolumeGoal<=0)throw new Error('Invalid monthly funding goal');await this.pool.query(`insert into monthly_funding_goals(id,year,month,funded_loan_goal,funded_volume_goal) values($1,$2,$3,$4,$5) on conflict(year,month) do update set funded_loan_goal=excluded.funded_loan_goal,funded_volume_goal=excluded.funded_volume_goal,updated_at=now()`,[randomUUID(),year,month,fundedLoanGoal,fundedVolumeGoal]);return this.monthlyFundingGoal(year,month);}
  async dashboard(){const latest=`left join lateral (select metadata from loan_stage_events where loan_id=l.id order by occurred_at desc,received_at desc limit 1) e on true`,{year,month}=pacificYearMonth();const [counts,processorLoans,processorSlas,funded,assistantTasks,assistantSlas,processorBreaches,assistantExceptions,ctcRisk,fundingGoal]=await Promise.all([
    this.pool.query(`select count(*) filter(where l.current_stage <> 'LOAN_FUNDED') active_loans,count(*) filter(where l.current_stage='LOAN_SETUP') new_files,count(*) filter(where l.current_stage='UNDERWRITING_SUBMITTED') uw_submitted,count(*) filter(where l.current_stage='CLEAR_TO_CLOSE') clear_to_close,(select count(*) from assistant_tasks t join loans task_loan on task_loan.id=t.loan_id where task_loan.processing_eligible_at is not null and task_loan.kpi_tracking_started_at is not null and t.kpi_eligible and t.completed_at is null and t.due_at<now())+(select count(*) from sla_measurements m join loans sla_loan on sla_loan.id=m.loan_id where sla_loan.processing_eligible_at is not null and sla_loan.kpi_tracking_started_at is not null and m.state='breached') past_sla from loans l where l.processing_eligible_at is not null`),
    this.pool.query(`select l.current_stage "currentStage",coalesce(e.metadata->>'processor','Unassigned') processor from loans l ${latest} where l.processing_eligible_at is not null`),
    this.pool.query(`select coalesce(e.metadata->>'processor','Unassigned') processor,r.metric_key "metricKey",m.state,m.due_at "dueAt",m.evaluated_at "evaluatedAt" from sla_measurements m join sla_rules r on r.id=m.rule_id join loans l on l.id=m.loan_id ${latest} where l.processing_eligible_at is not null and l.kpi_tracking_started_at is not null and r.owner_role='processor'`),
    this.pool.query(`select coalesce(e.metadata->>'processor','Unassigned') processor from loan_stage_events f join loans l on l.id=f.loan_id ${latest} where l.processing_eligible_at is not null and f.event_type='LOAN_FUNDED' and f.occurred_at>=date_trunc('month',now())`),
    this.pool.query(`select coalesce(e.metadata->>'assistant','Unassigned') assistant,t.task_type "taskType",t.kpi_eligible "kpiEligible",t.applicable_at "applicableAt",t.due_at "dueAt",t.completed_at "completedAt" from assistant_tasks t join loans l on l.id=t.loan_id ${latest} where l.processing_eligible_at is not null and t.kpi_eligible`),
    this.pool.query(`select coalesce(e.metadata->>'assistant','Unassigned') assistant,r.metric_key "taskType",m.state,m.due_at "dueAt",m.evaluated_at "evaluatedAt" from sla_measurements m join sla_rules r on r.id=m.rule_id join loans l on l.id=m.loan_id ${latest} where l.processing_eligible_at is not null and l.kpi_tracking_started_at is not null and r.owner_role='assistant'`),
    this.pool.query(`select l.arive_display_loan_id "displayLoanId",coalesce(e.metadata->>'processor','Unassigned') processor,r.metric_key detail,m.due_at "dueAt" from sla_measurements m join sla_rules r on r.id=m.rule_id join loans l on l.id=m.loan_id ${latest} where l.processing_eligible_at is not null and r.owner_role='processor' and m.state='breached' limit 50`),
    this.pool.query(`select l.arive_display_loan_id "displayLoanId",coalesce(e.metadata->>'assistant','Unassigned') assistant,t.task_type detail,t.due_at "dueAt",case when t.due_at<now() then 'assistant-breached' else 'assistant-approaching' end kind from assistant_tasks t join loans l on l.id=t.loan_id ${latest} where l.processing_eligible_at is not null and t.completed_at is null and (t.due_at<now() or now()>=t.applicable_at + (t.due_at-t.applicable_at)*.8) union all select l.arive_display_loan_id,coalesce(e.metadata->>'assistant','Unassigned'),r.metric_key,m.due_at,'assistant-breached' from sla_measurements m join sla_rules r on r.id=m.rule_id join loans l on l.id=m.loan_id ${latest} where l.processing_eligible_at is not null and r.owner_role='assistant' and m.state='breached' limit 50`),
    this.pool.query(`select l.arive_display_loan_id "displayLoanId",coalesce(e.metadata->>'processor','Unassigned') processor,null assistant,'Clear to close' detail,'ctc-risk' kind from loans l ${latest} where l.processing_eligible_at is not null and l.current_stage='CLEAR_TO_CLOSE' and exists(select 1 from sla_measurements m join sla_rules r on r.id=m.rule_id where m.loan_id=l.id and lower(r.metric_key) like '%ctc%' and m.state in ('breached','at-risk')) union all select l.arive_display_loan_id,coalesce(e.metadata->>'processor','Unassigned'),null,'Processor Assistant assignment review','assistant-assignment' from loans l ${latest} where l.processing_eligible_at is not null and coalesce(e.metadata->>'assignmentException','')<>'' limit 50`),
    this.fundingSummary(year,month)
  ]);const c=counts.rows[0];const attention=[...processorBreaches.rows.map(row=>({...row,kind:'processor-breached'})),...assistantExceptions.rows,...ctcRisk.rows].map(row=>({kind:row.kind,displayLoanId:row.displayLoanId??'—',processor:row.processor??null,assistant:row.assistant??null,detail:row.detail?.replaceAll('_',' ')??'Assignment review',dueAt:row.dueAt??null}));return {...buildLiveDashboard({counts:{activeLoans:Number(c.active_loans),newFiles:Number(c.new_files),uwSubmitted:Number(c.uw_submitted),clearToClose:Number(c.clear_to_close),fundedMtd:fundingGoal.fundedCount.actual,pastSla:Number(c.past_sla)},processorLoans:processorLoans.rows,processorSlas:processorSlas.rows,funded:funded.rows,assistantTasks:assistantTasks.rows,assistantSlas:assistantSlas.rows,attention}),fundingGoal};}
  async health(){const q=await this.pool.query(`select count(*) filter(where processing_status='processed') processed,count(*) filter(where processing_status='failed') failed,count(*) filter(where processing_status='duplicate') duplicates,count(*) received,max(received_at) last from inbound_events`),recent=await this.pool.query(`select received_at,external_id,coalesce(payload->>'ariveDisplayLoanId','—') display_loan_id,coalesce(payload->>'currentLoanStatus','—') event_type,processing_status,failure_reason from inbound_events order by received_at desc limit 20`);const r=q.rows[0];return {connectionStatus:Number(r.processed)>0?'arive-connected':'not-connected',lastEventReceived:r.last,eventsReceivedToday:Number(r.received),eventsProcessed:Number(r.processed),failedEvents:Number(r.failed),duplicateEventsIgnored:Number(r.duplicates),loansSynced:Number((await this.pool.query('select count(*) count from loans')).rows[0].count),missingRequiredFields:0,recent:recent.rows.map(row=>({receivedAt:row.received_at,sourceEventId:row.external_id,ariveDisplayLoanId:row.display_loan_id,eventType:row.event_type,status:row.processing_status,auditNote:row.failure_reason??'Processed'}))};}
  /** Last definition deliberately scopes the operational File Detail to eligible loans. */
  async listLoans(search=''){
    const term=`%${search}%`;
    const result=await this.pool.query(`select l.id,l.arive_display_loan_id,l.current_stage,l.city,l.state,coalesce(e.metadata->>'processor','Unassigned') processor,coalesce(e.metadata->>'assistant','Unassigned') assistant,(select task_type from assistant_tasks t where t.loan_id=l.id and t.completed_at is null order by t.due_at asc nulls last limit 1) next_milestone,(select due_at from assistant_tasks t where t.loan_id=l.id and t.completed_at is null order by t.due_at asc nulls last limit 1) next_due_at from loans l left join lateral (select metadata from loan_stage_events where loan_id=l.id order by occurred_at desc,received_at desc limit 1) e on true where l.processing_eligible_at is not null and (coalesce(l.arive_display_loan_id,'') ilike $1 or coalesce(l.current_stage,'') ilike $1 or coalesce(l.city,'') ilike $1 or coalesce(l.state,'') ilike $1 or coalesce(e.metadata->>'processor','') ilike $1 or coalesce(e.metadata->>'assistant','') ilike $1) order by l.updated_at desc limit 250`,[term]);
    return {source:'live',loans:result.rows.map(row=>this.safeLoanRow(row))};
  }
  async loanDetail(loanKey){
    const loan=await this.pool.query(`select l.id,l.arive_display_loan_id,l.current_stage,l.city,l.state,coalesce(e.metadata->>'processor','Unassigned') processor,coalesce(e.metadata->>'assistant','Unassigned') assistant from loans l left join lateral (select metadata from loan_stage_events where loan_id=l.id order by occurred_at desc,received_at desc limit 1) e on true where l.id=$1 and l.processing_eligible_at is not null`,[loanKey]);
    if(!loan.rowCount)return null;
    const tasks=await this.pool.query(`select task_type,due_at,completed_at,status from assistant_tasks where loan_id=$1 order by due_at asc`,[loanKey]),processorSlas=await this.pool.query(`select r.metric_key,m.due_at,m.state from sla_measurements m join sla_rules r on r.id=m.rule_id where m.loan_id=$1 order by m.due_at asc`,[loanKey]);
    const detail=this.safeLoanRow(loan.rows[0]);
    return {...detail,processorSlas:processorSlas.rows.map(item=>({name:item.metric_key.replaceAll('_',' '),dueAt:item.due_at,status:item.state})),milestones:tasks.rows.map(task=>({name:task.task_type.replaceAll('_',' '),dueAt:task.due_at,completedAt:task.completed_at,status:task.completed_at?(new Date(task.completed_at)<=new Date(task.due_at)?'Completed':'Completed Late'):new Date(task.due_at)<new Date()?'Breached':new Date(task.due_at)-new Date()<8.5*3600000?'Due Soon':'On Track'}))};
  }
}
